////------------------------------------------------------------------------------
//// <auto-generated>
////     This code was generated by a tool.
////     Runtime Version:4.0.30319.42000
////
////     Changes to this file may cause incorrect behavior and will be lost if
////     the code is regenerated.
//// </auto-generated>
////------------------------------------------------------------------------------

//namespace Matter.legal.MatterCenter.Performance {
//    using System;
//    using System.Collections.Generic;
//    using System.Text;
//    using Microsoft.VisualStudio.TestTools.WebTesting;
//    using JWTokenWebTestPlugin;
    
    
//    [Priority(0)]
//    public class HomePageMatterCoded : WebTest {
        
//        private JWTokenWebTestPlugin testPlugin0 = new JWTokenWebTestPlugin();
        
//        public HomePageMatterCoded() {
//            this.Context.Add("TokenValue", "");
//            this.PreAuthenticate = true;
//            this.Proxy = "default";
//            this.testPlugin0.ClientId = "";
//            this.testPlugin0.AppKey = "";
//            this.testPlugin0.TokenValue = "TokenValue";
//            this.testPlugin0.Tenant = "";
//            this.testPlugin0.AadInstance = "";
//            this.testPlugin0.ToDoResourceId = "";
//            this.PreWebTest += new EventHandler<PreWebTestEventArgs>(this.testPlugin0.PreWebTest);
//            this.PostWebTest += new EventHandler<PostWebTestEventArgs>(this.testPlugin0.PostWebTest);
//            this.PreTransaction += new EventHandler<PreTransactionEventArgs>(this.testPlugin0.PreTransaction);
//            this.PostTransaction += new EventHandler<PostTransactionEventArgs>(this.testPlugin0.PostTransaction);
//            this.PrePage += new EventHandler<PrePageEventArgs>(this.testPlugin0.PrePage);
//            this.PostPage += new EventHandler<PostPageEventArgs>(this.testPlugin0.PostPage);
//        }
        
//        public override IEnumerator<WebTestRequest> GetRequestEnumerator() {
//            this.UserName = "matteradmin@msmatter.onmicrosoft.com";
//            this.PreRequestDataBinding += new EventHandler<PreRequestDataBindingEventArgs>(this.testPlugin0.PreRequestDataBinding);
//            this.PreRequest += new EventHandler<PreRequestEventArgs>(this.testPlugin0.PreRequest);
//            this.PostRequest += new EventHandler<PostRequestEventArgs>(this.testPlugin0.PostRequest);

//            WebTestRequest request1 = new WebTestRequest("https://matterwebapp.azurewebsites.net//");
//            request1.Timeout = 60;
//            request1.Headers.Add(new WebTestRequestHeader("Upgrade-Insecure-Requests", "1"));
//            request1.Headers.Add(new WebTestRequestHeader("Pragma", "no-cache"));
//            yield return request1;
//            request1 = null;

//            WebTestRequest request2 = new WebTestRequest("https://matterwebapp.azurewebsites.net//api/v1/user/getuserprofilepicture");
//            request2.ThinkTime = -1;
//            request2.Timeout = 60;
//            request2.Method = "POST";
//            request2.Headers.Add(new WebTestRequestHeader("Origin", "Https://matterwebapp.azurewebsites.net/"));
//            request2.Headers.Add(new WebTestRequestHeader("Content-Type", "application/json"));
//            request2.Headers.Add(new WebTestRequestHeader("Pragma", "no-cache"));
//            request2.Headers.Add(new WebTestRequestHeader("Authorization", this.Context["TokenValue"].ToString()));
//            request2.Headers.Add(new WebTestRequestHeader("Referer", "Https://matterwebapp.azurewebsites.net/"));       
//            StringHttpBody request2Body = new StringHttpBody();
//            request2Body.ContentType = "application/json";
//            request2Body.InsertByteOrderMark = false;
//            request2Body.BodyString = "{\"Url\":\"https://msmatter.sharepoint.com\"}";
//            request2.Body = request2Body;
//            yield return request2;
//            request2 = null;

//            WebTestRequest request3 = new WebTestRequest("https://matterwebapp.azurewebsites.net//api/v1/matter/cancreate");
//            request3.ThinkTime = -1;
//            request3.Timeout = 60;
//            request3.Method = "POST";
//            request3.Headers.Add(new WebTestRequestHeader("Origin", "https://matterwebapp.azurewebsites.net/"));
//            request3.Headers.Add(new WebTestRequestHeader("Content-Type", "application/json"));
//            request3.Headers.Add(new WebTestRequestHeader("Pragma", "no-cache"));
//            request3.Headers.Add(new WebTestRequestHeader("Authorization", this.Context["TokenValue"].ToString()));
//            StringHttpBody request3Body = new StringHttpBody();
//            request3Body.ContentType = "application/json";
//            request3Body.InsertByteOrderMark = false;
//            request3Body.BodyString = "{\"Url\":\"https://msmatter.sharepoint.com/sites/catalog\"}";
//            request3.Body = request3Body;
//            yield return request3;
//            request3 = null;

//            WebTestRequest request4 = new WebTestRequest("https://matterwebapp.azurewebsites.net//api/v1/shared/help");
//            request4.Timeout = 60;
//            request4.Method = "POST";
//            request4.Headers.Add(new WebTestRequestHeader("Origin", "https://matterwebapp.azurewebsites.net/"));
//            request4.Headers.Add(new WebTestRequestHeader("Content-Type", "application/json"));
//            request4.Headers.Add(new WebTestRequestHeader("Pragma", "no-cache"));
//            request4.Headers.Add(new WebTestRequestHeader("Authorization", this.Context["TokenValue"].ToString()));
//            StringHttpBody request4Body = new StringHttpBody();
//            request4Body.ContentType = "application/json";
//            request4Body.InsertByteOrderMark = false;
//            request4Body.BodyString = "{\"Client\":{\"Url\":\"https://msmatter.sharepoint.com/sites/catalog\"},\"SelectedPage\":" +
//                "\"0\"}";
//            request4.Body = request4Body;
//            yield return request4;
//            request4 = null;

//            WebTestRequest request5 = new WebTestRequest("https://matterwebapp.azurewebsites.net//api/v1/matter/cancreate");
//            request5.Timeout = 60;
//            request5.Method = "POST";
//            request5.Headers.Add(new WebTestRequestHeader("Origin", "https://matterwebapp.azurewebsites.net/"));
//            request5.Headers.Add(new WebTestRequestHeader("Content-Type", "application/json"));
//            request5.Headers.Add(new WebTestRequestHeader("Pragma", "no-cache"));
//            request5.Headers.Add(new WebTestRequestHeader("Authorization", this.Context["TokenValue"].ToString()));
//            StringHttpBody request5Body = new StringHttpBody();
//            request5Body.ContentType = "application/json";
//            request5Body.InsertByteOrderMark = false;
//            request5Body.BodyString = "{\"Url\":\"https://msmatter.sharepoint.com/sites/catalog\"}";
//            request5.Body = request5Body;
//            yield return request5;
//            request5 = null;
//        }
//    }
//}
