//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Legal.MatterCenter.Utility {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Log {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Log() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.Legal.MatterCenter.Utility.Log", typeof(Log).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MM-dd-yyyy HH:mm:ss:fffffff.
        /// </summary>
        internal static string Azure_RowKey_Date_Format {
            get {
                return ResourceManager.GetString("Azure_RowKey_Date_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DefaultEndpointsProtocol=https;AccountName=[Enter Azure account name, e.g. mattercenterlogaccount];AccountKey=[Enter Account Key for this storage account, e.g. BDLWAl5dePECEtzZTZEBdpPrTrIzUehs4odNasdaw5d8l7pKl2o0uOz4QQqQ+hBQwavQEwRWAasy8xhdxb78vow==].
        /// </summary>
        internal static string CloudStorageConnectionString {
            get {
                return ResourceManager.GetString("CloudStorageConnectionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1001.
        /// </summary>
        internal static string EventViewer_EventID {
            get {
                return ResourceManager.GetString("EventViewer_EventID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LCADMS.
        /// </summary>
        internal static string EventViewer_LogName {
            get {
                return ResourceManager.GetString("EventViewer_LogName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LCADMS.
        /// </summary>
        internal static string EventViewer_Source {
            get {
                return ResourceManager.GetString("EventViewer_Source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TRUE.
        /// </summary>
        internal static string IsDeployedOnAzure {
            get {
                return ResourceManager.GetString("IsDeployedOnAzure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TRUE.
        /// </summary>
        internal static string IsLoggingOnAzure {
            get {
                return ResourceManager.GetString("IsLoggingOnAzure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Enter name of the table on Azure storage where all error/exception log, e.g. MatterCenterLogTable].
        /// </summary>
        internal static string UtilityLogTableName {
            get {
                return ResourceManager.GetString("UtilityLogTableName", resourceCulture);
            }
        }
    }
}
