//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Legal.MatterCenter.SharePointAppWeb.App_LocalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class FindDocument {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FindDocument() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.Legal.MatterCenter.SharePointAppWeb.App_LocalResources.FindDocument", typeof(FindDocument).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attach Documents.
        /// </summary>
        internal static string AttachButtonText {
            get {
                return ResourceManager.GetString("AttachButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One or more of your selected documents failed to attach:.
        /// </summary>
        internal static string AttachFailureMessage {
            get {
                return ResourceManager.GetString("AttachFailureMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attaching &lt;span id=\&quot;currentDocumentCount\&quot;&gt;&lt;/span&gt;of {0} documents... &lt;div&gt;Do not close Matter Center until all documents are attached.&lt;/div&gt;.
        /// </summary>
        internal static string AttachInProgressMessage {
            get {
                return ResourceManager.GetString("AttachInProgressMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documents successfully attached..
        /// </summary>
        internal static string AttachSuccessMessage {
            get {
                return ResourceManager.GetString("AttachSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search by ID, document title, or client name.
        /// </summary>
        internal static string AutoComplete_Placeholder {
            get {
                return ResourceManager.GetString("AutoComplete_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Attach Documents.
        /// </summary>
        internal static string Event_Name_Attach_Document {
            get {
                return ResourceManager.GetString("Event_Name_Attach_Document", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document you are trying to unpin is not pinned..
        /// </summary>
        internal static string Failure_Invalid_Unpin {
            get {
                return ResourceManager.GetString("Failure_Invalid_Unpin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong.
        /// </summary>
        internal static string Failure_Message {
            get {
                return ResourceManager.GetString("Failure_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MSITOfficeAuthor.
        /// </summary>
        internal static string FilterRefinerAuthor {
            get {
                return ResourceManager.GetString("FilterRefinerAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MCCheckoutUser.
        /// </summary>
        internal static string FilterRefinerCheckOutUser {
            get {
                return ResourceManager.GetString("FilterRefinerCheckOutUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created.
        /// </summary>
        internal static string FilterRefinerCreated {
            get {
                return ResourceManager.GetString("FilterRefinerCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MCDocumentClientName.
        /// </summary>
        internal static string FilterRefinerDocumentClient {
            get {
                return ResourceManager.GetString("FilterRefinerDocumentClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DocumentOwner.
        /// </summary>
        internal static string FilterRefinerPinnedAuthor {
            get {
                return ResourceManager.GetString("FilterRefinerPinnedAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DocumentCheckoutUser.
        /// </summary>
        internal static string FilterRefinerPinnedCheckOutUser {
            get {
                return ResourceManager.GetString("FilterRefinerPinnedCheckOutUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DocumentCreatedDate.
        /// </summary>
        internal static string FilterRefinerPinnedCreatedDate {
            get {
                return ResourceManager.GetString("FilterRefinerPinnedCreatedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DocumentClient.
        /// </summary>
        internal static string FilterRefinerPinnedDocumentClient {
            get {
                return ResourceManager.GetString("FilterRefinerPinnedDocumentClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DocumentModifiedDate.
        /// </summary>
        internal static string FilterRefinerPinnedModifiedDate {
            get {
                return ResourceManager.GetString("FilterRefinerPinnedModifiedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to loadCheckboxColumn;loadDocumentTypeIcon;loadNameColumn;loadEllipsisColumn;genericColumn;loadClientMatterID_Column;loadDateColumn;genericColumn;genericColumn;loadCheckedOutToUser;loadDateColumn.
        /// </summary>
        internal static string ListViewColumnFomatter {
            get {
                return ResourceManager.GetString("ListViewColumnFomatter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document;Client;Client.Matter ID;Modified date;Author;Document version;Checked out to;Created date.
        /// </summary>
        internal static string ListViewColumnPickerFields {
            get {
                return ResourceManager.GetString("ListViewColumnPickerFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CheckBox;DocType;FileName;ECB;MCDocumentClientName;MCDocumentClientID;MCModifiedDate;MSITOfficeAuthor;MCVersionNumber;MCCheckoutUser;Created.
        /// </summary>
        internal static string ListViewColumnValueFields {
            get {
                return ResourceManager.GetString("ListViewColumnValueFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 21;30;210;30;210;160;205;150;210;220;200.
        /// </summary>
        internal static string ListViewColumnWidth {
            get {
                return ResourceManager.GetString("ListViewColumnWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check Box,NA;DocType,NA;Document,singleselect;ECB,NA;Client,singleselect;Client.Matter ID,NA;Modified date,date.
        /// </summary>
        internal static string ListViewDefaultColumns {
            get {
                return ResourceManager.GetString("ListViewDefaultColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FileExtension.
        /// </summary>
        internal static string ListViewDocumentExtension {
            get {
                return ResourceManager.GetString("ListViewDocumentExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DocumentOWAUrl.
        /// </summary>
        internal static string ListViewDocumentOWAUrl {
            get {
                return ResourceManager.GetString("ListViewDocumentOWAUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path.
        /// </summary>
        internal static string ListViewDocumentPath {
            get {
                return ResourceManager.GetString("ListViewDocumentPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SPWebUrl.
        /// </summary>
        internal static string ListViewDocumentSPWebUrl {
            get {
                return ResourceManager.GetString("ListViewDocumentSPWebUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open this Document,editdocument;View Matter Details,gotoMatterSites;Pin this Document,pin;Unpin this Document,unpin.
        /// </summary>
        internal static string ListViewECBActions {
            get {
                return ResourceManager.GetString("ListViewECBActions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View this document$|$Go to this document\&apos;s matter details$|$Add this document to Pinned Documents$|$Remove this document from Pinned Documents.
        /// </summary>
        internal static string ListViewECBActionsTitle {
            get {
                return ResourceManager.GetString("ListViewECBActionsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to view the document menu.
        /// </summary>
        internal static string ListViewECBMenuTitle {
            get {
                return ResourceManager.GetString("ListViewECBMenuTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check Box,NA;DocType,NA;Document,singleselect;ECB,NA;Client,singleselect;Client.Matter ID,NA;Modified date,date;Author,singleselect;Document version,NA;Checked out to,singleselect;Created date,date.
        /// </summary>
        internal static string ListViewHeaderName {
            get {
                return ResourceManager.GetString("ListViewHeaderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select all$|$Doc type$|$Click to sort by document name$|$$|$Click to sort by client name$|$Click to sort by Client.Matter ID$|$Click to sort by last modified date$|$Click to sort by document author$|$Click to sort by version$|$Click to sort by who has documents checked out$|$Click to sort by created date.
        /// </summary>
        internal static string ListViewHeaderNameTitle {
            get {
                return ResourceManager.GetString("ListViewHeaderNameTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RefinableString12.
        /// </summary>
        internal static string ListViewMatterIDPropertyName {
            get {
                return ResourceManager.GetString("ListViewMatterIDPropertyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check Box,NA;DocType,NA;ECB,NA.
        /// </summary>
        internal static string ListViewNonDataColumns {
            get {
                return ResourceManager.GetString("ListViewNonDataColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CalClientMatterId.
        /// </summary>
        internal static string ListViewPinnedClientMatterIDPropertyName {
            get {
                return ResourceManager.GetString("ListViewPinnedClientMatterIDPropertyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CheckBox;DocType;DocumentName;ECB;DocumentClient;CalClientMatterId;DocumentModifiedDate;DocumentOwner;DocumentVersion;DocumentCheckoutUser;DocumentCreatedDate.
        /// </summary>
        internal static string ListViewPinnedColumnValueFields {
            get {
                return ResourceManager.GetString("ListViewPinnedColumnValueFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DocumentClientId.
        /// </summary>
        internal static string ListViewPinnedDocumentClientIDPropertyName {
            get {
                return ResourceManager.GetString("ListViewPinnedDocumentClientIDPropertyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DocumentMatterId.
        /// </summary>
        internal static string ListViewPinnedMatterIDPropertyName {
            get {
                return ResourceManager.GetString("ListViewPinnedMatterIDPropertyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DocumentName.
        /// </summary>
        internal static string ListViewPinnedTitleProperty {
            get {
                return ResourceManager.GetString("ListViewPinnedTitleProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FileName.
        /// </summary>
        internal static string ListViewTitleProperty {
            get {
                return ResourceManager.GetString("ListViewTitleProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait while the documents load..
        /// </summary>
        internal static string Loading_Document {
            get {
                return ResourceManager.GetString("Loading_Document", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do not select more than five documents to attach at one time..
        /// </summary>
        internal static string MaxAttachedMessage {
            get {
                return ResourceManager.GetString("MaxAttachedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No results found..
        /// </summary>
        internal static string No_Data_Message {
            get {
                return ResourceManager.GetString("No_Data_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NA.
        /// </summary>
        internal static string No_Data_String {
            get {
                return ResourceManager.GetString("No_Data_String", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no pinned documents..
        /// </summary>
        internal static string No_Pinned_Documents {
            get {
                return ResourceManager.GetString("No_Pinned_Documents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search document assigned to Me.
        /// </summary>
        internal static string Search_Assigned_To_Me {
            get {
                return ResourceManager.GetString("Search_Assigned_To_Me", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search entire Matter Center.
        /// </summary>
        internal static string Search_Entire_DMS {
            get {
                return ResourceManager.GetString("Search_Entire_DMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All documents,alldata;My documents,mydata;Pinned documents,pinneddata.
        /// </summary>
        internal static string SearchDropdownFields {
            get {
                return ResourceManager.GetString("SearchDropdownFields", resourceCulture);
            }
        }
    }
}
