//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Legal.MatterCenter.SharePointAppWeb.App_LocalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MatterProvision {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MatterProvision() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.Legal.MatterCenter.SharePointAppWeb.App_LocalResources.MatterProvision", typeof(MatterProvision).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        internal static string Create_Button_Text {
            get {
                return ResourceManager.GetString("Create_Button_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create and Notify.
        /// </summary>
        internal static string Create_Notify_Button_Text {
            get {
                return ResourceManager.GetString("Create_Notify_Button_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to However an issue occurred and the custom view was not created..
        /// </summary>
        internal static string Create_View_Failure {
            get {
                return ResourceManager.GetString("Create_View_Failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Control.
        /// </summary>
        internal static string Edit_Matter_Mandatory_Permission_Level {
            get {
                return ResourceManager.GetString("Edit_Matter_Mandatory_Permission_Level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assign Permission Failure: .
        /// </summary>
        internal static string Error_Assign_Permission {
            get {
                return ResourceManager.GetString("Error_Assign_Permission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assign permission to at least one team member.
        /// </summary>
        internal static string Error_Assign_Permission_To_User {
            get {
                return ResourceManager.GetString("Error_Assign_Permission_To_User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Associate Content Type Failure: .
        /// </summary>
        internal static string Error_Associate_Content_Type {
            get {
                return ResourceManager.GetString("Error_Associate_Content_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter users that are conflicted with this matter..
        /// </summary>
        internal static string Error_Blocked_Users {
            get {
                return ResourceManager.GetString("Error_Blocked_Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter users who are not conducting conflict check.
        /// </summary>
        internal static string Error_Conflict_Check_User {
            get {
                return ResourceManager.GetString("Error_Conflict_Check_User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A conflict check must be completed prior to provisioning this matter..
        /// </summary>
        internal static string Error_Conflict_Exists {
            get {
                return ResourceManager.GetString("Error_Conflict_Exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the conflict reviewers name (for auditing purposes)..
        /// </summary>
        internal static string Error_Conflict_Reviewer_User {
            get {
                return ResourceManager.GetString("Error_Conflict_Reviewer_User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error in creation of matter: .
        /// </summary>
        internal static string Error_Create_Matter {
            get {
                return ResourceManager.GetString("Error_Create_Matter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select primary matter type.
        /// </summary>
        internal static string Error_Default_Matter_Type {
            get {
                return ResourceManager.GetString("Error_Default_Matter_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a different Matter name. A matter with same name already exists..
        /// </summary>
        internal static string Error_Duplicate_Matter {
            get {
                return ResourceManager.GetString("Error_Duplicate_Matter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Landing page of this Matter is already created. Kindly delete existing landing page or please enter a different Matter name..
        /// </summary>
        internal static string Error_Duplicate_MatterLandingPage {
            get {
                return ResourceManager.GetString("Error_Duplicate_MatterLandingPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OneNote library for this Matter is already created. Kindly delete the library or please enter a different Matter name..
        /// </summary>
        internal static string Error_Duplicate_OneNoteLibrary {
            get {
                return ResourceManager.GetString("Error_Duplicate_OneNoteLibrary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide at least one user who has Full Control permission on this matter..
        /// </summary>
        internal static string Error_Edit_Matter_Mandatory_Permission {
            get {
                return ResourceManager.GetString("Error_Edit_Matter_Mandatory_Permission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter valid users in the Assign Permission users list.
        /// </summary>
        internal static string Error_Invalid_Assign_Permission_Users {
            get {
                return ResourceManager.GetString("Error_Invalid_Assign_Permission_Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter valid users in Conflicted Users list.
        /// </summary>
        internal static string Error_Invalid_Block_Users {
            get {
                return ResourceManager.GetString("Error_Invalid_Block_Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter individual who is not conflicted.
        /// </summary>
        internal static string Error_Invalid_User {
            get {
                return ResourceManager.GetString("Error_Invalid_User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter at least one {0} for this matter..
        /// </summary>
        internal static string Error_Mandatory_Role {
            get {
                return ResourceManager.GetString("Error_Mandatory_Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a description for this matter..
        /// </summary>
        internal static string Error_Matter_Description {
            get {
                return ResourceManager.GetString("Error_Matter_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a matter ID..
        /// </summary>
        internal static string Error_Matter_ID {
            get {
                return ResourceManager.GetString("Error_Matter_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create Matter Landing page, continuing with other steps....
        /// </summary>
        internal static string Error_Matter_Landing_Page_Creation {
            get {
                return ResourceManager.GetString("Error_Matter_Landing_Page_Creation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a matter name..
        /// </summary>
        internal static string Error_Matter_Title {
            get {
                return ResourceManager.GetString("Error_Matter_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occurred and the matter was not created. Error Code: {0}.
        /// </summary>
        internal static string Error_Provisioning_Process {
            get {
                return ResourceManager.GetString("Error_Provisioning_Process", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a client for this matter..
        /// </summary>
        internal static string Error_Select_Client {
            get {
                return ResourceManager.GetString("Error_Select_Client", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select matter type by area of law for this matter..
        /// </summary>
        internal static string Error_Select_Content_Type {
            get {
                return ResourceManager.GetString("Error_Select_Content_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the date on which the conflict check was performed..
        /// </summary>
        internal static string Error_Select_Date {
            get {
                return ResourceManager.GetString("Error_Select_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter at least one {0} for this matter..
        /// </summary>
        internal static string Error_Select_User {
            get {
                return ResourceManager.GetString("Error_Select_User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share Matter Failure: .
        /// </summary>
        internal static string Error_Share_Matter {
            get {
                return ResourceManager.GetString("Error_Share_Matter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid text which contains only alphanumeric characters, spaces &amp; hyphen.
        /// </summary>
        internal static string Error_Special_Character {
            get {
                return ResourceManager.GetString("Error_Special_Character", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stamp Properties Failure: .
        /// </summary>
        internal static string Error_Stamp_Properties {
            get {
                return ResourceManager.GetString("Error_Stamp_Properties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter valid conflicted user from people picker.
        /// </summary>
        internal static string Error_Valid_Block_Users {
            get {
                return ResourceManager.GetString("Error_Valid_Block_Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the valid date in MM/DD/YYYY format.
        /// </summary>
        internal static string Error_Valid_Date {
            get {
                return ResourceManager.GetString("Error_Valid_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid Matter name which contains only alphanumeric characters and spaces.
        /// </summary>
        internal static string Error_Valid_Matter_Name {
            get {
                return ResourceManager.GetString("Error_Valid_Matter_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -900000005.
        /// </summary>
        internal static string ErrorCode_MatterLandingPageExists {
            get {
                return ResourceManager.GetString("ErrorCode_MatterLandingPageExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to true.
        /// </summary>
        internal static string Flag_Send_Email {
            get {
                return ResourceManager.GetString("Flag_Send_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step &lt;span&gt;{0}&lt;/span&gt; of {1}.
        /// </summary>
        internal static string Header_Display_Step {
            get {
                return ResourceManager.GetString("Header_Display_Step", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to However an issue occurred and the email notification was not sent. Team members will see the new Matter in Search Matter soon..
        /// </summary>
        internal static string Share_Matter_Failure {
            get {
                return ResourceManager.GetString("Share_Matter_Failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [A-Za-z0-9_]+[-A-Za-z0-9_, .]*.
        /// </summary>
        internal static string Special_Character_Expression_Matter_Description {
            get {
                return ResourceManager.GetString("Special_Character_Expression_Matter_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [A-Za-z0-9_]+[-A-Za-z0-9_, ]*.
        /// </summary>
        internal static string Special_Character_Expression_Matter_Id {
            get {
                return ResourceManager.GetString("Special_Character_Expression_Matter_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [A-Za-z0-9-_]+[A-Za-z0-9-_ ]*.
        /// </summary>
        internal static string Special_Character_Expression_Matter_Title {
            get {
                return ResourceManager.GetString("Special_Character_Expression_Matter_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matter is successfully created. You can find recently created matter over &lt;a target=&apos;_blank&apos; href=&apos;{0}&apos;&gt;here&lt;/a&gt;..
        /// </summary>
        internal static string Success_Matter_Creation {
            get {
                return ResourceManager.GetString("Success_Matter_Creation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step 1/3: Creating matter library and OneNote library....
        /// </summary>
        internal static string Success_Matter_Step_1 {
            get {
                return ResourceManager.GetString("Success_Matter_Step_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step 2/3: Assigning permissions to matter library and OneNote library, associating Content Types, creating view and matter landing page....
        /// </summary>
        internal static string Success_Matter_Step_2 {
            get {
                return ResourceManager.GetString("Success_Matter_Step_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step 3/3: Updating metadata of matter library and sharing matter with the users....
        /// </summary>
        internal static string Success_Matter_Step_3 {
            get {
                return ResourceManager.GetString("Success_Matter_Step_3", resourceCulture);
            }
        }
    }
}
