var oTestConfiguration = {
    sSiteURL: "http://mattermaqdevsite.azurewebsites.net",
    sValidMatterName: "Test Matter 112233",
    sValidMatterClientURL: "https://lcadms.sharepoint.com/sites/microsoft",
    sInvalidMatterName: "Microsoft Test",
    sInvalidMatterURL: "https://lcadms.sharepoint.com/sites/microsoft",
    sSourceIconURL: "https://lcadms.sharepoint.com/_layouts/15/images/icsourceicon.gif",
    sEmailSubject: "CELA Project Center Feedback and Support request",
    sLearnMoreLink: "http://www.microsoft.com/mattercenter",
    sOverwriteConfigFileName: "testEmail.eml",
    sSelectedClient: "A. Datum Corporation",
    sSelectedPracticeGroup: "Advertising, Marketing ＆ Promotions",
    sSelectedAreaOfLaw: "Advertising, Marketing ＆ Promotions",
    sActiveSubAreaOfLawTerm: "Advertising, Marketing ＆ Promotions",
    sFolderNames: "Email;Lorem;Ipsum",
    nGUIDLength: 32,
    sLocationURL: "https://mattermaqdevsite.azurewebsites.net&test=1&attempt=2|jasminetest.html",
    nDocumentCheckCount: 2,
    oClientObj: { id: 16761, name: "Microsoft", url: "https://lcadms.sharepoint.com/sites/microsoft" },
    oDocumentObject: {
        documentCheckoutUser: "MAQ User",
        documentClient: "Awesome Computers",
        documentClientId: "0016763",
        documentClientUrl: "https://lcadms.sharepoint.com/sites/awesomecomputers",
        documentCreatedDate: "2/11/2016 10:55:43 AM",
        documentExtension: "docx",
        documentIconUrl: "https://lcadms.sharepoint.com/_layouts/15/images/icdocx.gif",
        documentID: "17592407627949",
        documentMatter: "Test GitHub build",
        documentMatterId: "TGB001",
        documentMatterUrl: "https://lcadms.sharepoint.com/sites/AwesomeComputers/727f57900ca2b473b99b25f9e36506d0/Forms",
        documentModifiedDate: "2/8/2016 1:06:00 PM",
        documentName: "Test Document.docx",
        documentOWAUrl: "https://lcadms.sharepoint.com/sites/AwesomeComputers/_layouts/15/WopiFrame.aspx?sourcedoc={ADF55595-76D7-4131-8FE9-807989BA166D}&file=Test%20Document.docx&action=default&DefaultItemOpen=1",
        documentOwner: "MAQ User",
        documentParentUrl: "https://lcadms.sharepoint.com/sites/AwesomeComputers/727f57900ca2b473b99b25f9e36506d0/Forms/AllItems.aspx",
        documentUrl: "https://lcadms.sharepoint.com/sites/AwesomeComputers/_layouts/15/WopiFrame.aspx?sourcedoc={ADF55595-76D7-4131-8FE9-807989BA166D}&file=Test%20Document.docx&action=default&DefaultItemOpen=1",
        documentVersion: "2.0",
        pinType: "Pin"
    },
    oMatterObject: {
        matterName: "Default Matter",
        matterDescription: "Test Matter",
        matterCreatedDate: "19/08/2016",
        matterUrl: "https://lcadms.sharepoint.com/sites/subsiteclient/SitePages/6cbca4ab447c87302d3a1f0e3c32985a.aspx",
        matterPracticeGroup: "Business Transactions",
        matterAreaOfLaw: "Family Business",
        matterSubAreaOfLaw: "Family Business",
        matterClientUrl: "https://lcadms.sharepoint.com/sites/subsiteclient",
        matterClient: "Microsoft",
        matterClientId: "578cfafb-59eb-4f4c-b219-47886c61e384",
        hideUpload: true,
        matterID: "1516561262162",
        matterResponsibleAttorney: "CELA",
        matterModifiedDate: "19/08/2016",
        matterGuid: "578cfafb-59eb-4f4c-b219-47886c61e384",
        pinType: 'unpin'
    }
};

var oEnvironmentConfiguration = {
    tenantID: "9a689192-bfc9-4d08-94b9-64b31bc60540",
    clientID: "61394aba-09ba-4e25-ae32-e10805c6841b",
    instanceURL: "https://login.microsoftonline.com/"
};