var uiconfigs =
{
    "CreateMatter": {
        "Tab1HeaderTitle": "Step 1: Select a client and provide basic information for your new matter.",
        "Tab2HeaderTitle": "Step 2: Confirm that a conflict check was conducted and specify who should be conflicted from or given access to this matter.",
        "Tab3HeaderTitle": "Step 3: When you've entered all relevant information for your new matter, create the matter and notify your team.",
        "ButtonNextText": "Next",
        "ButtonPreviousText": "Previous",
        "ButtonCreateText": "Create",
        "Tab2NoSearchResultText": "No Results Found",
        "Tab1Type1Header1Label1": "Select a Practice Group",
        "Tab1Type1Footer1Label1": "Please select primary matter type before you save.",
        "Tab1SiteColumn1Caption": "Area of Law",
        "Tab1SiteColumn2Caption": "Sub Area of Law (select matter type)",
        "Tab1SiteColumn3Caption": "Matter Type",
        "Tab1Type1Label1": "select primary matter type",
        "Tab1ButtonAddTitle": "Add",
        "Tab1ButtonRemoveTitle": "Remove",
        "MenuImageTitle": "Matter Center menu",
        "MenuImageCaption": "menu",
        "Tab1ButtonCloseTitle": "Close",
        "Tab1ButtonSelectType": "Select Type",
        "Tab1ImageLoadingAltText": "Loading...",
        "MenuItem1LinkTitle": "Home",
        "MenuItem2LinkTitle": "Search matters",
        "MenuItem3LinkTitle": "Search documents",
        "MenuItem1LinkText": "Home",
        "MenuItem2LinkText": "Matters",
        "MenuItem3LinkText": "Documents",
        "ButtonSaveText": "Save",
        "MenuImageOpenTitle": "Open App Switcher",
        "MenuImageCloseTitle": "Close App Switcher",
        "ButtonDeleteText": "Delete",
        "Tab1LeftButtonAltText": "Left",
        "Tab1RighttButtonAltText": "Right",
        "Tab3SectionText": "You have entered all of the necessary information to create this matter. After you click Create and Notify, the matter will be created and all team members will receive an email containing a link to this matter's location. ",
        "LabelNotificationPopupForExternalSharingText": "The following recipent is outside your organization. Would you still like to invite them to the Assigned Team?",
        "RemoveLinkText": "Remove",
        "ConfirmLinkText": "Confirm",
        "Tab1Dropdown1Label": "Client Name",
        "Tab1Header": "Open Matter",
        "Tab2Header": "Assign Permission",
        "Tab3Header": "Create and Notify",
        "Tab2Checkbox1Lebal": "Conflict check conducted (must be complete prior to provisioning matter)",
        "Tab2Textbox1Label": "Who conducted the conflict check?",
        "Tab2DateLabel": "Date Conducted",
        "Tab2RadioButton1Label": "Conflict Identified?",
        "Tab2RadioButton1Option1": "Yes",
        "Tab2RadioButton1Option2": "No",
        "Tab2Textbox2Label": "Conflicted Users",
        "Tab1Textbox1Label": "Client ID",
        "Tab2Textbox2PlaceHolder": "Enter and select names",
        "Tab2RadioButton2Label": "Would you like this matter to be secured only to the assigned team?",
        "Tab2RadioButton2Option1": "Yes",
        "Tab2RadioButton2Option2": "No",
        "Tab2TeamHeader": "Assign Team",
        "Tab2Textbox3Label": "Name",
        "Tab2Textbox3PlaceHolder": "Enter and select names",
        "Tab2Deopdown1Label": "Role",
        "Tab2Deopdown2Label": "Permission Level",
        "Tab2AddMoreHeaderLabel": "Add More Names",
        "Tab1Textbox2Label": "Matter Name",
        "Tab3CheckBox1Text": "Include calendar",
        "Tab3CheckBox2Text": "Include RSS Feeds",
        "Tab3CheckBox3Text": "Include email notification",
        "Tab3CheckBox4Text": "Include Tasks",
        "Tab3ButtonText": "Create and Notify",
        "Tab1Textbox2PlaceholderText": "Enter a name for this matter",
        "Tab1Textbox3Label": "Matter ID",
        "Tab1Textbox3PlaceholderText": "Enter a matter ID",
        "Tab1Textbox4Label": "Matter Description",
        "Tab1Textbox4PlaceholderText": "Enter a brief description of the matter",
        "Tab1Textbox5Label": "Matter Type (click Select to define the practice group and area of law)",
        "Tab1DrpDownLevel1DefaultSelectOption": "Select a practice group",
        "Tab1TermsSelectionSearchPlaceHolderText": "Search by typing",
        "Tab1LabelFinalTypeText": "MatterType",
        "Tab1LabelPrimaryTypeText": "Please select primary matter type",
        "Tab1LabelPrimaryTypeBeforeSaveText": "Please select primary matter type before you save.",
        "Tab1ButtonSaveSelectiponText": "Save Selections"
    },
    "DocumentDashboard": {
        "LinkImageLoadingTitle": "Matter Center Home",
        "ImageLoadingAltText": "Matter Center",
        "Image1EmailAttachmentText": "Email as attachment",
        "Image2EmailAttachmentLinkText": "Email as link",
        "Image3EmailRemovalAttachmentLinkText": "Remove attachment",
        "SearchDocumentPlaceholderText": "Search by document name, document ID, or keyword",
        "ImageAdvanceSearchAltText": "Drop Down",
        "ImageAdvanceSearchTitle": "Advanced search",
        "AdvSearchLabel1Text": "Clients",
        "AdvSearchLabel1FunctionParameterText": "client",
        "AdvSearchTextbox1PlaceholderText": "Enter or select a client",
        "AdvSearchSelectAllLinkText": "Select All",
        "AdvSearchSelectNoneLinkText": "Select None",
        "AdvSearchbuttonOkText": "Ok",
        "AdvSearchbuttonCancelText": "Cancel",
        "AdvSearchLabel2Text": "Author",
        "AdvSearchTextbox2PlaceholderText": "Document Author",
        "AdvSearchLabel3Text": "Date",
        "AdvSearchTextbox3PlaceholderText": "From",
        "AdvSearchTextbox4PlaceholderText": "To",
        "NoSearchResultMsgText": "No Results Found",
        "AdvSearchButtonSearchText": "Search",
        "Tab1HeaderText": "My documents",
        "Tab2HeaderText": "All documents",
        "Tab3HeaderText": "Pinned documents",
        "ImageMailCartIconTitle": "Review the contents of your mail cart and send the selected documents to your OneDrive or via email.",
        "ImageMailCartIconAltText": "Mail Cart",
        "LabelSortByText": "Sort by:",
        "LabelSortByTitle": "Sort By",
        "DrpDownOption1Text": "None",
        "DrpDownOption2Text": "Alphabetical",
        "DrpDownOption3Text": "Created date",
        "DrpDownOption4Text": "Modified date",
        "MattersPreLoadingMsgText": " Please wait while the Documents load.",
        "AttachmentLoadingText": "Loading...",
        "GridColumn1Header": "Document",
        "GridColumn2Header": "Client",
        "GridColumn3Header": "Author",
        "GridColumn4Header": "Modified Date",
        "GridColumn5Header": "Document ID",
        "GridColumn6Header": "Version"
    },
    "Documents": {
        "EllipsisLink4Text": "Unpin this Document",
        "StartDatePlaceHolder": "Start mm/dd/yyyy",
        "EndDatePlaceHolder": "End mm/dd/yyyy",
        "ImageWarningTitle": "Warning",
        "ImageWarningAltText": "Warning icon",
        "AttachmentSuccessfullyMsgText": "Documents successfully attached.",
        "AttachmentProgressingText": "Attaching",
        "AttachmentProgressingWarningText": "Do not close Matter Center until all documents are attached.",
        "AttachmentLoadingText": "Loading...",
        "ButtonOkText": "Ok",
        "ImageClearTitle": "Clear",
        "LabelCloseText": "Close",
        "ClearFilterFromLabelText": "Clear filters from ",
        "NoFilterMatchMsgTitle": "There are no items that match this filter",
        "NoFilterMatchMsgText": "There are no items that match this filter",
        "LabelDocumentText": "documents...",
        "LabelOfText": "of",
        "ImageClearAltText": "Clear filters",
        "FilterSearchPlaceholderText": "Search",
        "EllipsisDocTypeIconAltText": "Document type icon",
        "FlyoutLable1Text": "Matter",
        "FlyoutLable2Text": "Document ID",
        "GridColumn8Header": "Created Date",
        "Dropdown1Item1": "All Documents",
        "Dropdown1Item2": "My Documents",
        "Dropdown1Item3": "Pinned Documents",
        "SearchPlaceholderText": "Search by ID, or document or client name",
        "NoDataSearchText": "Nothing matches your search term or the filter you selected. Please try again.<br>If you applied a filter, remove it to get back to your list.<br>Search suggestions:<br><ul><li>Make sure all words are spelled correctly</li><li>Try different keywords</li><li>Try searching by the matter name or client name</li><li>Try more general search terms</li></ul>",
        "GridColumn1Header": "Document",
        "GridColumn2Header": "Client",
        "GridColumn3Header": "Client.MatterID",
        "GridColumn4Header": "Modified Date",
        "GridColumn5Header": "Author",
        "GridColumn6Header": "Document Version",
        "GridColumn7Header": "Checked out to",
        "HeaderText": "All Documents",
        "EllipsisLink1Text": "Open this Document",
        "EllipsisLink2Text": "View Matter Details",
        "EllipsisLink3Text": "Pin this Document",
        "FlyoutButton1Text": "Open document",
        "FlyoutButton2Text": "View document details"
    },
    "Header": {
        "MenuImage1Title": "Matter center menu",
        "MenuImage1Caption": "menu",
        "MenuImage1OpenTitle": "Open App Switcher",
        "MenuImage1CloseTitle": "Close App Switcher",
        "Menu1Option1Title": "Home",
        "Menu1Option2Title": "Search matters",
        "Menu1Option3Title": "Search documents",
        "Menu1Option1Text": "Home",
        "Menu1Option2Text": "Matters",
        "Menu1Option3Text": "Documents",
        "ContextualHelpImageTitle": "Matter center help",
        "ContextualHelpHeader": "Matter Center For Outlook",
        "ContextualHelpNoLinkText": "There are no help links available.",
        "ContextualHelpFooterLink1Label": "Matter Center Aisling Support",
        "LogoImageTitle": "Matter center home",
        "ContextualHelpLabel1": "Get to know this view",
        "ContextualHelpLabel2": "How do I get Project Center on my device?",
        "MatterCenterSupportLink": "mailto:support@supportsite.com",
        "ContextualHelpFooterLink1Title": "Write an email to support",
        "ContextualHelpFooterLabel": "Questions? Contact ",
        "ContextualHelpAltText": "Contextual Help",
        "ContextualHelpFlyoutAltText": "Close flyout",
        "CloseTitle": "Close",
        "DashboardMenuImageUpperCaption": "Matter Center",
        "DashboardMenuImageLowerCaption": "for Office 365",
        "ImageOpenHamburgerTitle": "View links",
        "DashboardHeaderSearchPlaceholderText": "Search SharePoint",
        "DashboardSearchIconTitle": "Search",
        "HamburgerMenuOption3Text": "Settings",
        "FooterMenuOption4Text": "Microsoft",
        "FooterMenuOption1Text": "Feedback & Support",
        "FooterMenuOption2Text": "Privacy & Cookies",
        "FooterMenuOption3Text": "Terms of use",
        "ProfilePictureLabelText": "Profile Picture",
        "LabelSingOutText": "Sign Out",
        "ImageCloseHamburgerTitle": "Close"
    },
    "MatterDashboard": {
        "LinkImageLoadingTitle": "Matter Center Home",
        "ImageLoadingAltText": "Matter Center",
        "ImageCloseTitle": "Close",
        "AttachmentLoadingText": "Loading...",
        "SearchTextboxPlaceholderText": "Search by document name, document ID, or keyword",
        "ImageAdvanceSearchAltText": "Drop Down",
        "ImageAdvanceSearchTitle": "Advanced search",
        "AdvSearchLabel1Text": "Clients",
        "AdvSearchTextbox1PlaceholderText": "Enter or select a client",
        "AdvSearchSelectAllLinkText": "Select All",
        "AdvSearchSelectNoneLinkText": "Select None",
        "AdvSearchbuttonOkText": "Ok",
        "AdvSearchbuttonCancelText": "Cancel",
        "AdvSearchLabel2Text": "Practice Group",
        "AdvSearchTextbox2PlaceholderText": "Enter or select a practice group",
        "AdvSearchLabel3Text": "Area of Law",
        "AdvSearchTextbox3PlaceholderText": "Enter or select an area of law",
        "AdvSearchLabel4Text": "Date",
        "AdvSearchTextbox4PlaceholderText": "From",
        "AdvSearchTextbox5PlaceholderText": "To",
        "AdvSearchButtonSearchText": "Search",
        "Tab1HeaderText": "My matters",
        "Tab2HeaderText": "All matters ",
        "Tab3HeaderText": "Pinned matters",
        "ButtonExportText": "Export",
        "LabelSortByText": "Sort by:",
        "DrpDownOption1Text": "None",
        "DrpDownOption2Text": "Alphabetical",
        "DrpDownOption3Text": "Created date",
        "NoSearchResultMsgText": "No results found.",
        "Button1DuplicateContentTitle": "Matter Center will compare all content and data associated with the two documents. Navigating away from this screen will cancel the content check.",
        "Button1DuplicateContentText": "Perform content check",
        "Button2SaveLatestVersionTitle": "The file will be saved as the latest version of the existing document that has same title. Matter Center will retain all prior versions of the document.",
        "Button2SaveLatestVersionText": "Save as latest version",
        "Button3AppendDateTitle": "The file will be saved as new, separate document with the current date and time added to the end of the file name.",
        "Button3AppendDateText": "Append date to file name and save",
        "Button4CancelUploadTitle": "This document will not be uploaded and you will return to the previous screen.",
        "Button4CancelUploadText": "Cancel upload",
        "Image1ContentCheckText": "Checking content",
        "UploadCompleteLabel1Text": "Upload complete.",
        "CloseIconText": "X",
        "AttachmentPopupHeaderText": "Drag and drop items to folders on the right",
        "AttachmentPopupHeaderItem1Text": "Items",
        "AttachmentPopupHeaderItem2Text": "Folders",
        "AttachmentEditImageTitle": "Edit attachment name",
        "AttachmentEditImageAltText": "Edit",
        "AttachmentSaveImageTitle": "Save attachment name",
        "AttachmentSaveImageText": "Save",
        "AttachmentUploadSuccessfullyImageAltText": "Uploaded successfully",
        "AttachmentIconImageAltText": "attachment icon",
        "AttachmentTestTitle": "Test attachments",
        "AttachmentEmptyText": "No files uploaded",
        "AttachmentPopupFooterImageCapetion": "You can also drag and drop files from your desktop.",
        "MattersPreLoadingMsgText": "Please wait while the Matters load.",
        "GridColumn1Header": "Matter",
        "GridColumn2Header": "Client",
        "GridColumn3Header": "Client.Matter ID",
        "GridColumn4Header": "Modified Date",
        "GridColumn5Header": "Responsible attorney",
        "AdvSearchLabel1InternalFuncParamText": "client",
        "AdvSearchLabel2InternalFuncParamText": "level1",
        "AdvSearchLabel3InternalFuncParamText": "level2"
    },
    "Matters": {
        "EllipsisLink5Text": "Unpin this matter",
        "AttachmentEditImageTitle": "Edit attachment name",
        "AttachmentEditImageAltText": "Edit",
        "AttachmentSaveImageTitle": "Save attachment name",
        "AttachmentSaveImageText": "Save",
        "AttachmentUploadSuccessfullyImageAltText": "Uploaded successfully",
        "AttachmentIconImageAltText": "attachment icon",
        "AttachmentTestTitle": "Test attachments",
        "AttachmentEmptyText": "No files uploaded",
        "AttachmentBreadcrumAltText": "Root",
        "AttachmentFolderAltText": "Documents",
        "FilterSearchPlaceholderText": "Search",
        "ClearFilterText": "Clear filters from ",
        "NoFilterMatchMsgTitle": "There are no items that match this filter",
        "NoFilterMatchMsgText": "There are no items that match this filter",
        "ImageCloseText": "Close",
        "ImageClearTitle": "Clear",
        "ImageClearAltText": "Clear filters",
        "ClearFilterFromLabelText": "Clear filters from ",
        "ImageWarningAltText": "Warning Message",
        "Button1DuplicateContentTitle": "Matter Center will compare all content and data associated with the two documents. Navigating away from this screen will cancel the content check.",
        "Button1DuplicateContentText": "Perform content check",
        "Button2SaveLatestVersionTitle": "The file will be saved as the latest version of the existing document that has same title. Matter Center will retain all prior versions of the document.",
        "Button2SaveLatestVersionText": "Save as latest version",
        "Button3AppendDateTitle": "The file will be saved as new, separate document with the current date and time added to the end of the file name.",
        "Button3AppendDateText": "Append date to file name and save",
        "Button4CancelUploadTitle": "This document will not be uploaded and you will return to the previous screen.",
        "Button4CancelUploadText": "Cancel upload",
        "Button5OkTitle": "This document will not be uploaded and you will return to the previous screen.",
        "Button5OkText": "Ok",
        "Image1ContentCheckText": "Checking content  ",
        "Button6CancelText": "Cancel",
        "UploadCompleteLabel1Text": "Upload complete.",
        "CloseIconText": "x",
        "StartDatePlaceHolder": "Start mm/dd/yyyy",
        "EndDatePlaceHolder": "End mm/dd/yyyy",
        "GridColumn8Header": "Area of Law",
        "AttachmentLoadingText": "Loading...",
        "GridColumn5Header": "Responsible Attorney",
        "GridColumn6Header": "Sub Area of Law",
        "GridColumn7Header": "Open Date",
        "Dropdown1Item1": "All Matters",
        "Dropdown1Item2": "My Matters",
        "Dropdown1Item3": "Pinned Matters",
        "SearchPlaceholderText": "Search by ID, or matter or client name",
        "NoDataSearchText": "Nothing matches your search term or the filter you selected. Please try again.<br>If you applied a filter, remove it to get back to your list.<br>Search suggestions:<br><ul><li>Make sure all words are spelled correctly</li><li>Try different keywords</li><li>Try searching by the matter name or client name</li><li>Try more general search terms</li></ul>",
        "GridColumn1Header": "Matter",
        "GridColumn2Header": "Client",
        "GridColumn3Header": "Client.MatterID",
        "GridColumn4Header": "Modified Date",
        "HeaderText": "All Matters",
        "EllipsisLink1Text": "Upload to this Matter",
        "EllipsisLink2Text": "View Matter Details",
        "EllipsisLink3Text": "Go to Matter OneNote",
        "EllipsisLink4Text": "Pin this matter",
        "FlyoutButton1Text": "View matter details",
        "FlyoutButton2Text": "Upload to a matter",
        "AttachmentPopupHeaderText": "Drag and drop items to folders on the right",
        "AttachmentPopupFooterImageCapetion": "You can also drag and drop files from your desktop.",
        "AttachmentPopupHeaderItem1Text": "Items",
        "AttachmentPopupHeaderItem2Text": "Folders",
        "AttachmentPopupHeaderText": "Upload to a matter"
    },
    "Navigation": {
        "MenuItem1LinkTitle": "Home",
        "MenuItem1LinkTitle": "Search matters",
        "MenuItem1LinkTitle": "Search documents",
        "NameTitle": "Matter",
        "HeaderBarLink1Title": "Learn more about matter center",
        "HeaderBarLink2Title": "Remove this section",
        "MenuImageOpenTitle": "Open App Switcher",
        "MenuImageCloseTitle": "Close App Switcher",
        "HeaderBarLink1Text": "LearnMore",
        "HomeMenuText": "Home",
        "Image1Title": "Search matters",
        "Image2Title": "Search documents",
        "HelpRequesURL": oEnvironmentConfiguration.tenantUrl + "/sites/catalog",
        "FooterLabel": "Questions? Contact",
        "MenuImageCaption": "menu",
        "MenuImageTitle": "Matter center menu",
        "MenuItem1LinkText": "Home",
        "MenuItem2LinkText": "Matters",
        "MenuItem3LinkText": "Documents",
        "LogoImageTitle": "Matter center home",
        "ContextualHelpImageTitle": "Matter center help",
        "ContextualHelpLabel1": "Get to know this view",
        "ContextualHelpLink1Text": "Home in Outlook and Word",
        "ContextualHelpLink1URL": "https://microsoft.sharepoint.com/teams/celapcconfig/Shared%20Documents/CELA%20Project%20Center%20End%20User%20Guide_24.pdf#Home_in_Outlook_and_Word ",
        "ContextualHelpLabel2": "How do I get Project Center on my device?",
        "ContextualHelpLink2URL": "https://microsoft.sharepoint.com/teams/celapcconfig/Shared%20Documents/CELA%20Project%20Center%20End%20User%20Guide_24.pdf#Enabling_Project_Center",
        "ContextualHelpFooterLink1Label": "Matter Center Aisling Support",
        "MatterCenterSupportLink": "mailto:support@supportsite.com",
        "ContextualHelpFooterLink1Title": "Write an email to support",
        "ContextualHelpHeader": "Matter Center For Outlook",
        "ContextualHelpFooterLabel": "Questions? Contact ",
        "HeaderBarLabel": "Welcome to Matter Center! Upload, share, and save your documents here.",
        "Image1Caption": "Matters",
        "Image2Caption": "Documents",
        "HeaderBarLink1URL": "http://www.microsoft.com/mattercenter",
        "HeaderBarLink2Text": "dismiss",
        "Image3Caption": "Upload attachments",
        "Image4Caption": "Create a new matter",
        "Image5Caption": "Go to Matter Center Home",
        "FooterLink1Title": "Matter Center Support",
        "FooterLink1Text": "Matter Center Support",
        "FooterLink1URL": "mailto:lcaweb2@microsoft.com?subject=CELA Project Center Feedback and Support request",
        "Image3Title": "Upload documents to a matter",
        "Image4Title": "Create a new matter site",
        "Image5Title": "Go to the web home page"
    },
    "Settings": {
        "Label1HeaderText": "Settings",
        "Label2Text": "Click on a name to configure matter creation options for that client.",
        "Label3Text": "Client Name",
        "Label5Section1HeaderText": "Select default values",
        "Label6Section1HeaderText": "Default selections will be editable when a new matter is created.",
        "Label7DefaultValue1TitleText": "Matter Name",
        "Label8DefaultValue1TitleDescription": "Enter default text to appear when a new matter is created. For example, a matter name prefix or suffix, or naming convention instructions.This text can be removed or changed when a new matter is created.",
        "Label9DefaultValue2TitleText": "Matter ID",
        "Label10DefaultValue2TitleDescription": "ID numbers must be manually entered when a new matter is created. Enter default text, such as ID prefix or suffix, or numbering instructions. This text can be removed or changed when a new matter is created.",
        "Label11DefaultValue3HeaderText": "Set a default matter type by selecting a Practice group, Area of law, and Sub areas of law below.",
        "Label12DefaultValue3TitleText": "Default to restricting access to an assigned team?",
        "Label13DefaultValue3TitleDescription": "This can be changed when a new matter is created. If you select yes, you can either define a default team below or leave the team permission blank.",
        "Radio1Option1Text": "Yes",
        "Radio1Option2Text": "No",
        "Label14DefaultValue4HeaderText": "Assign team permission",
        "Label15DefaultValue4Text": "Name",
        "Label16DefaultValue4Text": "Role",
        "Label17DefaultValue4Text": "Permission level",
        "Textbox1DefaultValue4PlaceholdertText": "Enter and select names",
        "Label18DefaultValue4NoResultsFoundText": "No Results Found",
        "Label19DefaultValue4AddMoreText": "Add More",
        "Label20DefaultValue5Text": "Include email notification?",
        "Label21DefaultValue6Text": "Include calendar?",
        "Label22DefaultValue7Text": "Include tasks?",
        "Label23DefaultValue8Text": "Include RSS Feeds?",
        "Label24Section2HeaderText": "Set matter options",
        "Label25Section2HeaderText": "These settings will not be editable when a new matter is created.",
        "Label26Section2Text": "Make the matter description field required?",
        "Label27Section2DescriptionText": "Selecting No will allow new matters to be saved without a description",
        "Label28Section2Text": "Do matters need conflict check data?",
        "Label29Section2DescriptionText": "Selecting No will remove the conflict check declaration fields from new matters",
        "Label30Section2Text": "Show or hide role?",
        "Label31Section2Text": "Show matter id?",
        "Label32Section2Text": "Matter Id Configuration",
        "Radio2Option1Text": "Guid",
        "Radio2Option2Text": "Date Time",
        "Radio2Option3Text": "Custom",
        "ButtonSaveText": "Save",
        "ButtonCancelText": "Cancel",
        "ImageLoadingAltText": "Loading...",
        "Label4Selection1HeaderText": "This page shows the current settings for this client's new matters. The first section allows you to set new matter default selections, which can be changed when a matter is created. The second section defines settings that can not be changed when a new matter is created. No changes are required, and any changes made will not affect existing matters.",
        "DeleteTitleText": "Delete",
        "Radio2Option2ValueText": "DateTime",
        "Label33Section2Text": "Your changes have been saved. Go back to ",
        "Label34Section2Text": "Clients"
    }
};
