//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Legal.MatterCenter.SharePointAppWeb.App_GlobalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Constants {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Constants() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.Legal.MatterCenter.SharePointAppWeb.App_GlobalResources.Constants", typeof(Constants).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /AddToMailCart.
        /// </summary>
        internal static string Add_To_Mail_Cart {
            get {
                return ResourceManager.GetString("Add_To_Mail_Cart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #.
        /// </summary>
        internal static string Admin_Support_URL {
            get {
                return ResourceManager.GetString("Admin_Support_URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage documents: view, edit, or pin a document.
        /// </summary>
        internal static string All_Documents_Message {
            get {
                return ResourceManager.GetString("All_Documents_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All documents.
        /// </summary>
        internal static string All_Documents_Title {
            get {
                return ResourceManager.GetString("All_Documents_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Forms/AllItems.aspx.
        /// </summary>
        internal static string All_Items_Extension {
            get {
                return ResourceManager.GetString("All_Items_Extension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage matters: upload emails or documents to a matter, review matter details, or pin matters.
        /// </summary>
        internal static string All_Matters_Message {
            get {
                return ResourceManager.GetString("All_Matters_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All matters.
        /// </summary>
        internal static string All_Matters_Title {
            get {
                return ResourceManager.GetString("All_Matters_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App Landing Page.
        /// </summary>
        internal static string App_Name_App_Landing_Page {
            get {
                return ResourceManager.GetString("App_Name_App_Landing_Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provision Matters.
        /// </summary>
        internal static string App_Name_Provision_Matters {
            get {
                return ResourceManager.GetString("App_Name_Provision_Matters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Documents.
        /// </summary>
        internal static string App_Name_Search_Documents {
            get {
                return ResourceManager.GetString("App_Name_Search_Documents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Matters.
        /// </summary>
        internal static string App_Name_Search_Matters {
            get {
                return ResourceManager.GetString("App_Name_Search_Matters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string App_Name_Settings_Page {
            get {
                return ResourceManager.GetString("App_Name_Settings_Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web Dashboard.
        /// </summary>
        internal static string App_Name_Web_Dashboard {
            get {
                return ResourceManager.GetString("App_Name_Web_Dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Enter app redirect URL for tenant, e.g. https://[TENANTNAME].sharepoint.com/sites/catalog/_layouts/15/appredirect.aspx].
        /// </summary>
        internal static string App_Redirect_URL {
            get {
                return ResourceManager.GetString("App_Redirect_URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Enter Application Insights ID specific to environment, e.g. a70d9cb8-e6f0-c8e7-0cbb8d1d-a4cf342c].
        /// </summary>
        internal static string Application_Insight_App_Id {
            get {
                return ResourceManager.GetString("Application_Insight_App_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MCAreaofLaw.
        /// </summary>
        internal static string Area_Of_Law {
            get {
                return ResourceManager.GetString("Area_Of_Law", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MSITOfficeAuthor.
        /// </summary>
        internal static string Author {
            get {
                return ResourceManager.GetString("Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browser.
        /// </summary>
        internal static string Browser {
            get {
                return ResourceManager.GetString("Browser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Enter URL of the central repository where all the common lists are stored, e.g. https://[TENANTNAME].sharepoint.com/sites/catalog].
        /// </summary>
        internal static string Central_Repository_Url {
            get {
                return ResourceManager.GetString("Central_Repository_Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occurred while checking out the document:.
        /// </summary>
        internal static string Check_Out_Document_Fail {
            get {
                return ResourceManager.GetString("Check_Out_Document_Fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File does not exist..
        /// </summary>
        internal static string Checked_Out_File_Not_Found {
            get {
                return ResourceManager.GetString("Checked_Out_File_Not_Found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It might have been moved or deleted..
        /// </summary>
        internal static string Checked_Out_File_Not_Found_Moved_Deleted {
            get {
                return ResourceManager.GetString("Checked_Out_File_Not_Found_Moved_Deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ClientID, ClientURL.
        /// </summary>
        internal static string Client_Custom_Properties {
            get {
                return ResourceManager.GetString("Client_Custom_Properties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ClientId.
        /// </summary>
        internal static string Client_Custom_Properties_Id {
            get {
                return ResourceManager.GetString("Client_Custom_Properties_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ClientURL.
        /// </summary>
        internal static string Client_Custom_Properties_Url {
            get {
                return ResourceManager.GetString("Client_Custom_Properties_Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MCClientID.
        /// </summary>
        internal static string Client_ID {
            get {
                return ResourceManager.GetString("Client_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MCClientName.
        /// </summary>
        internal static string Client_Name {
            get {
                return ResourceManager.GetString("Client_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ClientName.
        /// </summary>
        internal static string Client_Name_Search_Term {
            get {
                return ResourceManager.GetString("Client_Name_Search_Term", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clients.
        /// </summary>
        internal static string Client_Term_Set_Name {
            get {
                return ResourceManager.GetString("Client_Term_Set_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Enter Client ID of SharePoint App from the specific Tenancy, e.g. 4e55c7b2-eb66a-753e7-2679ac37be8b08].
        /// </summary>
        internal static string ClientID {
            get {
                return ResourceManager.GetString("ClientID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ..
        /// </summary>
        internal static string ClientID_MatterID_Separator {
            get {
                return ResourceManager.GetString("ClientID_MatterID_Separator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Clients.
        /// </summary>
        internal static string Clients {
            get {
                return ResourceManager.GetString("Clients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /CloseAdvanceSearch.
        /// </summary>
        internal static string Close_Advance_Search {
            get {
                return ResourceManager.GetString("Close_Advance_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div class=\&quot;ms-ChoiceField columnPickerCheckBox\&quot;&gt;&lt;input class=\&quot;ms-ChoiceField-input {3}\&quot; id=\&quot;options-checkbox-unselected{0}\&quot; type=\&quot;checkbox\&quot; onChange=\&quot;oCommonObject.onColumnPickerCheckboxClick({2},event)\&quot;/&gt;&lt;label class=\&quot;ms-ChoiceField-field {3}\&quot; for=\&quot;options-checkbox-unselected{0}\&quot;&gt;&lt;span class=\&quot;ms-Label columnOptionName\&quot; title=\&quot;{1}\&quot;&gt;{1}&lt;/span&gt;&lt;/label&gt;&lt;/div&gt;.
        /// </summary>
        internal static string ColumnPickerChunk {
            get {
                return ResourceManager.GetString("ColumnPickerChunk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MatterCenterTerms.
        /// </summary>
        internal static string Common_Term_Set_Group_Name {
            get {
                return ResourceManager.GetString("Common_Term_Set_Group_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content check has been aborted..
        /// </summary>
        internal static string Content_Check_Abort {
            get {
                return ResourceManager.GetString("Content_Check_Abort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Contextual help.
        /// </summary>
        internal static string Contextual_help {
            get {
                return ResourceManager.GetString("Contextual_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convenience copy only available.
        /// </summary>
        internal static string Convenience_copy_available {
            get {
                return ResourceManager.GetString("Convenience_copy_available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /CreateMatter.
        /// </summary>
        internal static string Create_Matter {
            get {
                return ResourceManager.GetString("Create_Matter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to created.
        /// </summary>
        internal static string Created {
            get {
                return ResourceManager.GetString("Created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created.
        /// </summary>
        internal static string Created_Date {
            get {
                return ResourceManager.GetString("Created_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mm/dd/yy.
        /// </summary>
        internal static string DatePickerFormat {
            get {
                return ResourceManager.GetString("DatePickerFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -1D.
        /// </summary>
        internal static string DatePickerFromMaxDate {
            get {
                return ResourceManager.GetString("DatePickerFromMaxDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -70:+70.
        /// </summary>
        internal static string DatePickerFromYearRange {
            get {
                return ResourceManager.GetString("DatePickerFromYearRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +0D.
        /// </summary>
        internal static string DatePickerToMaxDate {
            get {
                return ResourceManager.GetString("DatePickerToMaxDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -70:+10.
        /// </summary>
        internal static string DatePickerToYearRange {
            get {
                return ResourceManager.GetString("DatePickerToYearRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 60.
        /// </summary>
        internal static string Default_Filter_Container_Height {
            get {
                return ResourceManager.GetString("Default_Filter_Container_Height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 130.
        /// </summary>
        internal static string Default_Flyout_Container_Height {
            get {
                return ResourceManager.GetString("Default_Flyout_Container_Height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 90.
        /// </summary>
        internal static string Default_Flyout_Wrapper_Height {
            get {
                return ResourceManager.GetString("Default_Flyout_Wrapper_Height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 30.
        /// </summary>
        internal static string Default_Record_Height {
            get {
                return ResourceManager.GetString("Default_Record_Height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Delve.
        /// </summary>
        internal static string Delve {
            get {
                return ResourceManager.GetString("Delve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Enter Delve link URL, e.g. https://[TENANTNAME]-my.sharepoint.com/_layouts/15/me.aspx?q=].
        /// </summary>
        internal static string Delve_Link {
            get {
                return ResourceManager.GetString("Delve_Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to description.
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MatterCenterMatters.
        /// </summary>
        internal static string DMS_Matter_List_Name {
            get {
                return ResourceManager.GetString("DMS_Matter_List_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MatterCenterRoles.
        /// </summary>
        internal static string DMS_Role_List_Name {
            get {
                return ResourceManager.GetString("DMS_Role_List_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checked out copy available.
        /// </summary>
        internal static string Document_Checked_Out_Message {
            get {
                return ResourceManager.GetString("Document_Checked_Out_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MCDocumentClientID.
        /// </summary>
        internal static string Document_Client_ID {
            get {
                return ResourceManager.GetString("Document_Client_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MCDocumentClientName.
        /// </summary>
        internal static string Document_Client_Name {
            get {
                return ResourceManager.GetString("Document_Client_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dlcDocIdOWSText.
        /// </summary>
        internal static string Document_ID {
            get {
                return ResourceManager.GetString("Document_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Document info.
        /// </summary>
        internal static string Document_Info {
            get {
                return ResourceManager.GetString("Document_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MCModifiedDate.
        /// </summary>
        internal static string Document_Last_Modified_Time {
            get {
                return ResourceManager.GetString("Document_Last_Modified_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RefinableString12.
        /// </summary>
        internal static string Document_Matter_ID {
            get {
                return ResourceManager.GetString("Document_Matter_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RefinableString13.
        /// </summary>
        internal static string Document_Matter_Name {
            get {
                return ResourceManager.GetString("Document_Matter_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /DocumentTextboxSearch.
        /// </summary>
        internal static string Document_Textbox_Search {
            get {
                return ResourceManager.GetString("Document_Textbox_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /SitePages/documentDetails.aspx.
        /// </summary>
        internal static string DocumentLandingURL {
            get {
                return ResourceManager.GetString("DocumentLandingURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Edit Document.
        /// </summary>
        internal static string Edit_Document {
            get {
                return ResourceManager.GetString("Edit_Document", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have sufficient permissions to add or edit the team members.
        /// </summary>
        internal static string Edit_Matter_Access_Denied_Message {
            get {
                return ResourceManager.GetString("Edit_Matter_Access_Denied_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong while updating the users for the matter.
        /// </summary>
        internal static string Edit_Matter_Failure {
            get {
                return ResourceManager.GetString("Edit_Matter_Failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insufficient Query string parameters.
        /// </summary>
        internal static string Edit_Matter_Insufficient_Parameter {
            get {
                return ResourceManager.GetString("Edit_Matter_Insufficient_Parameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} cannot be empty..
        /// </summary>
        internal static string Edit_Matter_Validate_User {
            get {
                return ResourceManager.GetString("Edit_Matter_Validate_User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /EmailAttachment.
        /// </summary>
        internal static string Email_Attachment {
            get {
                return ResourceManager.GetString("Email_Attachment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string Email_Folder_Name {
            get {
                return ResourceManager.GetString("Email_Folder_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /EmailLink.
        /// </summary>
        internal static string Email_Link {
            get {
                return ResourceManager.GetString("Email_Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ^[\\s]*\\w+([-+.&apos;]\\w+)*@\\w+([-.]\\w+)*\\.\\w+([-.]\\w+)*[\\s]*$.
        /// </summary>
        internal static string Email_Validation_Regex {
            get {
                return ResourceManager.GetString("Email_Validation_Regex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Search.
        /// </summary>
        internal static string Enterprise_Search {
            get {
                return ResourceManager.GetString("Enterprise_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 125.
        /// </summary>
        internal static string Error_Code_Security_Group_Exists {
            get {
                return ResourceManager.GetString("Error_Code_Security_Group_Exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid characters in file name. Following characters are not allowed in file name:  ~ # % &amp;amp; * : &amp;lt; &amp;gt; ? /  \&quot;{ | }.
        /// </summary>
        internal static string Error_Invalid_Character {
            get {
                return ResourceManager.GetString("Error_Invalid_Character", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The search request is invalid, update the fields and try again..
        /// </summary>
        internal static string Error_Invalid_Search_Request {
            get {
                return ResourceManager.GetString("Error_Invalid_Search_Request", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error has occured while performing your last action. Please &lt;a class=&apos;ErrorPoUpLinks TryAgainLink&apos; href=&apos;&apos;&gt;try again&lt;/a&gt;. If this issue persist, please contact your &lt;a class=&apos;ErrorPoUpLinks AdminLink&apos; target=&apos;_blank&apos; href=&apos;&apos;&gt;administrator&lt;/a&gt;..
        /// </summary>
        internal static string Error_Pop_Up_Message {
            get {
                return ResourceManager.GetString("Error_Pop_Up_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -900000010.
        /// </summary>
        internal static string ErrorCodeOneDriveNotConfigured {
            get {
                return ResourceManager.GetString("ErrorCodeOneDriveNotConfigured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The documents were not sent as OneDrive is not yet configured, &lt;span class=\&quot;briefcaseURL\&quot; onClick=\&quot;window.open(\&apos;{0}\&apos;, \&apos;_blank\&apos;)\&quot;&gt;click here&lt;/span&gt; to configure your OneDrive and try again..
        /// </summary>
        internal static string ErrorMessageOneDriveNotConfigured {
            get {
                return ResourceManager.GetString("ErrorMessageOneDriveNotConfigured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong while sending documents to OneDrive..
        /// </summary>
        internal static string ErrorMessageSendToOneDrive {
            get {
                return ResourceManager.GetString("ErrorMessageSendToOneDrive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pages/.
        /// </summary>
        internal static string Events_Tracking_Pages {
            get {
                return ResourceManager.GetString("Events_Tracking_Pages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong!.
        /// </summary>
        internal static string Failure_Message {
            get {
                return ResourceManager.GetString("Failure_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fileextension.
        /// </summary>
        internal static string File_Extension {
            get {
                return ResourceManager.GetString("File_Extension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FileName.
        /// </summary>
        internal static string File_Name {
            get {
                return ResourceManager.GetString("File_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File is not available.
        /// </summary>
        internal static string File_Not_Available {
            get {
                return ResourceManager.GetString("File_Not_Available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to retrieve document check-out status..
        /// </summary>
        internal static string File_Not_Available_Error {
            get {
                return ResourceManager.GetString("File_Not_Available_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no items that match this filter.
        /// </summary>
        internal static string FilterFlyout_NoResult {
            get {
                return ResourceManager.GetString("FilterFlyout_NoResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 50.
        /// </summary>
        internal static string FilterFlyoutItemsPerCall {
            get {
                return ResourceManager.GetString("FilterFlyoutItemsPerCall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5.
        /// </summary>
        internal static string FilterLazyLoadingLimit {
            get {
                return ResourceManager.GetString("FilterLazyLoadingLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to T00:00:00Z.
        /// </summary>
        internal static string From_Date_Append_Time {
            get {
                return ResourceManager.GetString("From_Date_Append_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Go to Document Details page.
        /// </summary>
        internal static string Go_To_Document_Landing {
            get {
                return ResourceManager.GetString("Go_To_Document_Landing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Go to Matter Sites.
        /// </summary>
        internal static string Go_To_Matter_Sites {
            get {
                return ResourceManager.GetString("Go_To_Matter_Sites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /GoToOneNote.
        /// </summary>
        internal static string Go_To_OneNote {
            get {
                return ResourceManager.GetString("Go_To_OneNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 710.
        /// </summary>
        internal static string GridView_BreakPoint {
            get {
                return ResourceManager.GetString("GridView_BreakPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All column headers.
        /// </summary>
        internal static string GridViewAllColumnOption {
            get {
                return ResourceManager.GetString("GridViewAllColumnOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 21.
        /// </summary>
        internal static string GridViewItemsPerPage {
            get {
                return ResourceManager.GetString("GridViewItemsPerPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 95.
        /// </summary>
        internal static string GridViewLazyLoadingLimit {
            get {
                return ResourceManager.GetString("GridViewLazyLoadingLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to documenturl.
        /// </summary>
        internal static string GridViewPinnedDocumentUrl {
            get {
                return ResourceManager.GetString("GridViewPinnedDocumentUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home page.
        /// </summary>
        internal static string Home_page {
            get {
                return ResourceManager.GetString("Home_page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to image/.
        /// </summary>
        internal static string Image_ContentType {
            get {
                return ResourceManager.GetString("Image_ContentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Enter path of icon to display as per document selected e.g. https://[TENANTNAME].sharepoint.com/_layouts/15/images/ic{0}.gif].
        /// </summary>
        internal static string Image_Document_Icon {
            get {
                return ResourceManager.GetString("Image_Document_Icon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Enter path of icon to display for general document e.g. https://[TENANTNAME].sharepoint.com/_layouts/15/images/generaldocument.png].
        /// </summary>
        internal static string Image_General_Document {
            get {
                return ResourceManager.GetString("Image_General_Document", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 126.
        /// </summary>
        internal static string Incorrect_Team_Members_Code {
            get {
                return ResourceManager.GetString("Incorrect_Team_Members_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sending this file to One-Drive will not checkout the DMS version to you because its already checked out by another user..
        /// </summary>
        internal static string Info_Popup_Document_Already_Check_Out {
            get {
                return ResourceManager.GetString("Info_Popup_Document_Already_Check_Out", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When sending to your OneDrive the DMS version will be checked out to you until you check it back in..
        /// </summary>
        internal static string Info_Popup_Document_Check_Out {
            get {
                return ResourceManager.GetString("Info_Popup_Document_Check_Out", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error has occured while retrieving the document. Please &lt;a class=\\&apos;ErrorPoUpLinks ErrorTryAgainLink\\&apos; href=\\&apos;\\&apos;&gt;try again&lt;/a&gt;. If this issue persist, please contact your &lt;a class=\\&apos;ErrorPoUpLinks AdminLink\\&apos; target=\\&apos;_blank\\&apos; href=\\&apos;\\&apos;&gt;administrator&lt;/a&gt;\..
        /// </summary>
        internal static string Info_Popup_Error_Message {
            get {
                return ResourceManager.GetString("Info_Popup_Error_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to True.
        /// </summary>
        internal static string IsDeployedOnAzure {
            get {
                return ResourceManager.GetString("IsDeployedOnAzure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to isreadonlyuser.
        /// </summary>
        internal static string IsReadOnly {
            get {
                return ResourceManager.GetString("IsReadOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to True.
        /// </summary>
        internal static string IsTenantDeployment {
            get {
                return ResourceManager.GetString("IsTenantDeployment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LastModifiedTime.
        /// </summary>
        internal static string Last_Modified_Time {
            get {
                return ResourceManager.GetString("Last_Modified_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /_layouts/15/images/folder.gif.
        /// </summary>
        internal static string Layout_Folder_Icon {
            get {
                return ResourceManager.GetString("Layout_Folder_Icon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Enter URL of Learn More link used on App Landing page e.g. http://www.microsoft.com/mattercenter].
        /// </summary>
        internal static string Learn_More_Link {
            get {
                return ResourceManager.GetString("Learn_More_Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Learn More link.
        /// </summary>
        internal static string Learn_More_link_Name {
            get {
                return ResourceManager.GetString("Learn_More_link_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matter Center Briefcase.
        /// </summary>
        internal static string Legal_Briefcase_Folder_Name {
            get {
                return ResourceManager.GetString("Legal_Briefcase_Folder_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Enter URL of the service to be used for legal briefcase apps, e.g. https://[SERVICENAME].azurewebsites.net/LegalBriefcase.svc/].
        /// </summary>
        internal static string Legal_Briefcase_Service_Url {
            get {
                return ResourceManager.GetString("Legal_Briefcase_Service_Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait while the contextual help sections are being loaded....
        /// </summary>
        internal static string Load_Contextual_Help_Context {
            get {
                return ResourceManager.GetString("Load_Contextual_Help_Context", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait while clients are being loaded....
        /// </summary>
        internal static string Loading_Clients {
            get {
                return ResourceManager.GetString("Loading_Clients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /LocalUpload.
        /// </summary>
        internal static string Local_Upload {
            get {
                return ResourceManager.GetString("Local_Upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /MailAttachmentUpload.
        /// </summary>
        internal static string Mail_Attachment_Upload {
            get {
                return ResourceManager.GetString("Mail_Attachment_Upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matter Center Document(s).
        /// </summary>
        internal static string Mail_Cart_Mail_Subject {
            get {
                return ResourceManager.GetString("Mail_Cart_Mail_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MCCheckoutUser.
        /// </summary>
        internal static string Managed_Property_Document_CheckOutuser {
            get {
                return ResourceManager.GetString("Managed_Property_Document_CheckOutuser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MCVersionNumber.
        /// </summary>
        internal static string Managed_Property_Document_Version {
            get {
                return ResourceManager.GetString("Managed_Property_Document_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        internal static string Managed_Property_Title {
            get {
                return ResourceManager.GetString("Managed_Property_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Matter Center Support.
        /// </summary>
        internal static string Matter_Center_Support {
            get {
                return ResourceManager.GetString("Matter_Center_Support", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #.
        /// </summary>
        internal static string Matter_Center_Support_Email {
            get {
                return ResourceManager.GetString("Matter_Center_Support_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MCClientID.
        /// </summary>
        internal static string Matter_Client_Custom_Properties_Id {
            get {
                return ResourceManager.GetString("Matter_Client_Custom_Properties_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 255.
        /// </summary>
        internal static string Matter_Description_Max_Length {
            get {
                return ResourceManager.GetString("Matter_Description_Max_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MatterCenterMatterGUID.
        /// </summary>
        internal static string Matter_GUID {
            get {
                return ResourceManager.GetString("Matter_GUID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MCMatterID.
        /// </summary>
        internal static string Matter_ID {
            get {
                return ResourceManager.GetString("Matter_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MatterID.
        /// </summary>
        internal static string Matter_ID_Alias {
            get {
                return ResourceManager.GetString("Matter_ID_Alias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 75.
        /// </summary>
        internal static string Matter_Id_Max_Length {
            get {
                return ResourceManager.GetString("Matter_Id_Max_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Matter info.
        /// </summary>
        internal static string Matter_Info {
            get {
                return ResourceManager.GetString("Matter_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SitePages.
        /// </summary>
        internal static string Matter_Landing_Page_Repository {
            get {
                return ResourceManager.GetString("Matter_Landing_Page_Repository", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MCMatterName.
        /// </summary>
        internal static string Matter_Name {
            get {
                return ResourceManager.GetString("Matter_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 75.
        /// </summary>
        internal static string Matter_Name_Max_Length {
            get {
                return ResourceManager.GetString("Matter_Name_Max_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MatterName.
        /// </summary>
        internal static string Matter_Name_Search_Term {
            get {
                return ResourceManager.GetString("Matter_Name_Search_Term", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Enter URL of the service to be used for matter provisioning app, e.g. https://[SERVICENAME].azurewebsites.net/MatterProvision.svc/].
        /// </summary>
        internal static string Matter_Provision_Service_Url {
            get {
                return ResourceManager.GetString("Matter_Provision_Service_Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /MatterTextboxSearch.
        /// </summary>
        internal static string Matter_Textbox_Search {
            get {
                return ResourceManager.GetString("Matter_Textbox_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 200.
        /// </summary>
        internal static string Maximum_Filter_Container {
            get {
                return ResourceManager.GetString("Maximum_Filter_Container", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 273.
        /// </summary>
        internal static string Maximum_Flyout_Height {
            get {
                return ResourceManager.GetString("Maximum_Flyout_Height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Inputs.
        /// </summary>
        internal static string Message_No_Inputs {
            get {
                return ResourceManager.GetString("Message_No_Inputs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 73.
        /// </summary>
        internal static string Minimum_Flyout_Height {
            get {
                return ResourceManager.GetString("Minimum_Flyout_Height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 300.
        /// </summary>
        internal static string Minimum_Window_Size {
            get {
                return ResourceManager.GetString("Minimum_Window_Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3.
        /// </summary>
        internal static string Minlength_For_PeoplePicker {
            get {
                return ResourceManager.GetString("Minlength_For_PeoplePicker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage your recent documents: view, edit, or pin a document.
        /// </summary>
        internal static string My_Documents_Message {
            get {
                return ResourceManager.GetString("My_Documents_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My documents.
        /// </summary>
        internal static string My_Documents_Title {
            get {
                return ResourceManager.GetString("My_Documents_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage your recent matters: upload emails or documents to a matter, review matter details, or pin matters.
        /// </summary>
        internal static string My_Matters_Message {
            get {
                return ResourceManager.GetString("My_Matters_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My matters.
        /// </summary>
        internal static string My_Matters_Title {
            get {
                return ResourceManager.GetString("My_Matters_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No files uploaded.
        /// </summary>
        internal static string No_Files_Uploaded {
            get {
                return ResourceManager.GetString("No_Files_Uploaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no help links available..
        /// </summary>
        internal static string No_Help_Links_Message {
            get {
                return ResourceManager.GetString("No_Help_Links_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No results.
        /// </summary>
        internal static string No_Results_Autocomplete {
            get {
                return ResourceManager.GetString("No_Results_Autocomplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div class=&apos;noResultsText&apos;&gt;Nothing matches your search term or the filter you selected. Please try again.&lt;br /&gt;If you applied a filter, remove it to get back to your list.&lt;br /&gt;Search suggestions:&lt;br /&gt;&lt;ul&gt;&lt;li&gt;Make sure all words are spelled correctly&lt;/li&gt;&lt;li&gt;Try different keywords&lt;/li&gt;&lt;li&gt;Try searching by the matter name or client name&lt;/li&gt;&lt;li&gt;Try more general search terms&lt;/li&gt;&lt;/ul&gt;&lt;/div&gt;.
        /// </summary>
        internal static string No_Results_Message {
            get {
                return ResourceManager.GetString("No_Results_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Enter URL of office JS files, e.g. https://appsforoffice.microsoft.com/lib/1.1/hosted/office.js].
        /// </summary>
        internal static string Office_JS_URL {
            get {
                return ResourceManager.GetString("Office_JS_URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _OneNote.
        /// </summary>
        internal static string OneNoteLibrary_Name_Suffix {
            get {
                return ResourceManager.GetString("OneNoteLibrary_Name_Suffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /OpenAdvanceSearch.
        /// </summary>
        internal static string Open_Advance_Search {
            get {
                return ResourceManager.GetString("Open_Advance_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MCOpenDate.
        /// </summary>
        internal static string Open_Date {
            get {
                return ResourceManager.GetString("Open_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outlook.
        /// </summary>
        internal static string Outlook {
            get {
                return ResourceManager.GetString("Outlook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Only.
        /// </summary>
        internal static string Overwrite_Config_Property {
            get {
                return ResourceManager.GetString("Overwrite_Config_Property", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OWA.
        /// </summary>
        internal static string OWA {
            get {
                return ResourceManager.GetString("OWA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to docx,docm,odt,doc,dot,dotx,dotm,xlsx,xlsm,xlsb,ods,pptx,ppsx,odp,potx,pot,ppt,pps,pptm,potm,ppsm,ppam,vsdx,vsdm.
        /// </summary>
        internal static string OWA_Document_Extensions {
            get {
                return ResourceManager.GetString("OWA_Document_Extensions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vsdx,vsdm.
        /// </summary>
        internal static string OWA_Visio_Extensions {
            get {
                return ResourceManager.GetString("OWA_Visio_Extensions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _layouts/WopiFrame.aspx?sourcedoc={0}&amp;action=default&amp;DefaultItemOpen=1.
        /// </summary>
        internal static string OWA_WOPIFrameUrl {
            get {
                return ResourceManager.GetString("OWA_WOPIFrameUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to parentlink.
        /// </summary>
        internal static string Parent_Link {
            get {
                return ResourceManager.GetString("Parent_Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to path.
        /// </summary>
        internal static string Path {
            get {
                return ResourceManager.GetString("Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No results found.
        /// </summary>
        internal static string People_Picker_No_Results {
            get {
                return ResourceManager.GetString("People_Picker_No_Results", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;img src=\&quot;../Images/loadingcirclests16.gif\&quot; alt=\&quot;\&quot;/&gt;Checking content.
        /// </summary>
        internal static string Performing_Content_Check {
            get {
                return ResourceManager.GetString("Performing_Content_Check", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /personal/.
        /// </summary>
        internal static string Perosnal_URL_Separator {
            get {
                return ResourceManager.GetString("Perosnal_URL_Separator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /PinDocument.
        /// </summary>
        internal static string Pin_Document {
            get {
                return ResourceManager.GetString("Pin_Document", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /PinMatter.
        /// </summary>
        internal static string Pin_Matter {
            get {
                return ResourceManager.GetString("Pin_Matter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /PinSearch.
        /// </summary>
        internal static string Pin_Search {
            get {
                return ResourceManager.GetString("Pin_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /PinnedDocuments.
        /// </summary>
        internal static string Pinned_Documents {
            get {
                return ResourceManager.GetString("Pinned_Documents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage your pinned documents: view, edit, or unpin a document.
        /// </summary>
        internal static string Pinned_Documents_Message {
            get {
                return ResourceManager.GetString("Pinned_Documents_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pinned documents.
        /// </summary>
        internal static string Pinned_Documents_Title {
            get {
                return ResourceManager.GetString("Pinned_Documents_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /PinnedMatters.
        /// </summary>
        internal static string Pinned_Matters {
            get {
                return ResourceManager.GetString("Pinned_Matters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage your pinned matters: upload emails or documents to a matter, review matter details, or unpin matters.
        /// </summary>
        internal static string Pinned_Matters_Message {
            get {
                return ResourceManager.GetString("Pinned_Matters_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pinned matters.
        /// </summary>
        internal static string Pinned_Matters_Title {
            get {
                return ResourceManager.GetString("Pinned_Matters_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pdf;.
        /// </summary>
        internal static string PNG_Icon_Extensions {
            get {
                return ResourceManager.GetString("PNG_Icon_Extensions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MCPracticeGroup.
        /// </summary>
        internal static string Practice_Group {
            get {
                return ResourceManager.GetString("Practice_Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ContentTypeName.
        /// </summary>
        internal static string Practice_Group_Custom_Properties {
            get {
                return ResourceManager.GetString("Practice_Group_Custom_Properties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Practice Groups.
        /// </summary>
        internal static string Practice_Group_Term_Set_Name {
            get {
                return ResourceManager.GetString("Practice_Group_Term_Set_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Profile switch.
        /// </summary>
        internal static string Profile_switch {
            get {
                return ResourceManager.GetString("Profile_switch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Office.
        /// </summary>
        internal static string Querystring_Office {
            get {
                return ResourceManager.GetString("Querystring_Office", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outlook.
        /// </summary>
        internal static string Querystring_Outlook {
            get {
                return ResourceManager.GetString("Querystring_Outlook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OWA.
        /// </summary>
        internal static string Querystring_OWA {
            get {
                return ResourceManager.GetString("Querystring_OWA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /RecentDocuments.
        /// </summary>
        internal static string Recent_Documents {
            get {
                return ResourceManager.GetString("Recent_Documents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /RecentMatters.
        /// </summary>
        internal static string Recent_Matters {
            get {
                return ResourceManager.GetString("Recent_Matters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [A-Za-z0-9_, ]+(\.[-A-Za-z0-9_, ]*)*.
        /// </summary>
        internal static string Refiners_Regex {
            get {
                return ResourceManager.GetString("Refiners_Regex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7.
        /// </summary>
        internal static string Refresh_Local_Storage {
            get {
                return ResourceManager.GetString("Refresh_Local_Storage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10.
        /// </summary>
        internal static string RefreshTokenCookieExpiration {
            get {
                return ResourceManager.GetString("RefreshTokenCookieExpiration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /RemoveFromMailCart.
        /// </summary>
        internal static string Remove_From_Mail_Cart {
            get {
                return ResourceManager.GetString("Remove_From_Mail_Cart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /RenameMailAttachment.
        /// </summary>
        internal static string Rename_Mail_Attachment {
            get {
                return ResourceManager.GetString("Rename_Mail_Attachment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RequestToken.
        /// </summary>
        internal static string RequestTokenCookieName {
            get {
                return ResourceManager.GetString("RequestTokenCookieName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MCResponsibleAttorney.
        /// </summary>
        internal static string Responsible_Attorney {
            get {
                return ResourceManager.GetString("Responsible_Attorney", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /SaveRenamedMailAttachment.
        /// </summary>
        internal static string Save_Renamed_Mail_Attachment {
            get {
                return ResourceManager.GetString("Save_Renamed_Mail_Attachment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Save.
        /// </summary>
        internal static string Save_Settings {
            get {
                return ResourceManager.GetString("Save_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Enter URL of the service to be used for search apps, e.g. https://[SERVICENAME].azurewebsites.net/Search.svc/].
        /// </summary>
        internal static string Search_Service_Url {
            get {
                return ResourceManager.GetString("Search_Service_Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All matters,allmatters;My matters,mymatters;Pinned matters,pinnedmatters;Recent matters,recentmatters.
        /// </summary>
        internal static string SearchDropdownFields {
            get {
                return ResourceManager.GetString("SearchDropdownFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SendMail.
        /// </summary>
        internal static string Send_Mail_List_Name {
            get {
                return ResourceManager.GetString("Send_Mail_List_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /SendtoOneDrive.
        /// </summary>
        internal static string Send_to_OneDrive {
            get {
                return ResourceManager.GetString("Send_to_OneDrive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while sending documents to OneDrive. Error code :.
        /// </summary>
        internal static string Send_To_OneDrive_Error_Message {
            get {
                return ResourceManager.GetString("Send_To_OneDrive_Error_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /pages/Home.aspx.
        /// </summary>
        internal static string ServicePath_AppLandingPage {
            get {
                return ResourceManager.GetString("ServicePath_AppLandingPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /pages/finddocument.aspx.
        /// </summary>
        internal static string ServicePath_FindDocument {
            get {
                return ResourceManager.GetString("ServicePath_FindDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /pages/findmatter.aspx.
        /// </summary>
        internal static string ServicePath_FindMatter {
            get {
                return ResourceManager.GetString("ServicePath_FindMatter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /pages/MatterProvision.aspx.
        /// </summary>
        internal static string ServicePath_MatterProvision {
            get {
                return ResourceManager.GetString("ServicePath_MatterProvision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /pages/WebDashboard.aspx.
        /// </summary>
        internal static string ServicePath_WebDashboard {
            get {
                return ResourceManager.GetString("ServicePath_WebDashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div&gt;You do not have permission to access this page. If you feel you need to access this page, kindly contact your support &lt;a href=&apos;mailto:{0}&apos;&gt;team&lt;/a&gt; to grant you access.&lt;/div&gt;.
        /// </summary>
        internal static string Settings_Page_Access_Denied_Message {
            get {
                return ResourceManager.GetString("Settings_Page_Access_Denied_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /SitePages/Settings.aspx.
        /// </summary>
        internal static string SettingsPage {
            get {
                return ResourceManager.GetString("SettingsPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /_layouts/15/SignOut.aspx.
        /// </summary>
        internal static string Sign_Out_URL {
            get {
                return ResourceManager.GetString("Sign_Out_URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sitename.
        /// </summary>
        internal static string Site_Name {
            get {
                return ResourceManager.GetString("Site_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Enter URL of the SharePoint site, e.g. https://mytenant.sharepoint.com].
        /// </summary>
        internal static string Site_Url {
            get {
                return ResourceManager.GetString("Site_Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 54.
        /// </summary>
        internal static string Small_WindowSize_Flyout_Container_Height {
            get {
                return ResourceManager.GetString("Small_WindowSize_Flyout_Container_Height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 128.
        /// </summary>
        internal static string Small_WindowSize_Flyout_Height {
            get {
                return ResourceManager.GetString("Small_WindowSize_Flyout_Height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alphabetical ↑.
        /// </summary>
        internal static string Sort_Type_Alphabetical_ASC {
            get {
                return ResourceManager.GetString("Sort_Type_Alphabetical_ASC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alphabetical ↓.
        /// </summary>
        internal static string Sort_Type_Alphabetical_DESC {
            get {
                return ResourceManager.GetString("Sort_Type_Alphabetical_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created date ↑.
        /// </summary>
        internal static string Sort_Type_Date_Created_ASC {
            get {
                return ResourceManager.GetString("Sort_Type_Date_Created_ASC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created date ↓.
        /// </summary>
        internal static string Sort_Type_Date_Created_DESC {
            get {
                return ResourceManager.GetString("Sort_Type_Date_Created_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modified date ↑.
        /// </summary>
        internal static string Sort_Type_Date_Modified_ASC {
            get {
                return ResourceManager.GetString("Sort_Type_Date_Modified_ASC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modified date ↓.
        /// </summary>
        internal static string Sort_Type_Date_Modified_DESC {
            get {
                return ResourceManager.GetString("Sort_Type_Date_Modified_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        internal static string Sort_Type_None {
            get {
                return ResourceManager.GetString("Sort_Type_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relevant.
        /// </summary>
        internal static string Sort_Type_Relevant {
            get {
                return ResourceManager.GetString("Sort_Type_Relevant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to spweburl.
        /// </summary>
        internal static string SP_Web_Url {
            get {
                return ResourceManager.GetString("SP_Web_Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 148.
        /// </summary>
        internal static string Space_Above_Filter_Flyout {
            get {
                return ResourceManager.GetString("Space_Above_Filter_Flyout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MCSubAreaofLaw.
        /// </summary>
        internal static string Sub_Area_Of_Law {
            get {
                return ResourceManager.GetString("Sub_Area_Of_Law", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DocumentTemplates.
        /// </summary>
        internal static string Sub_Area_Of_Law_Document_Templates {
            get {
                return ResourceManager.GetString("Sub_Area_Of_Law_Document_Templates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Enter tenant URL of the Matter Center app, e.g. https://[TENANTNAME].sharepoint.com].
        /// </summary>
        internal static string Tenant_Url {
            get {
                return ResourceManager.GetString("Tenant_Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /SitePages/MatterCenterHome.aspx.
        /// </summary>
        internal static string TenantWebDashboard {
            get {
                return ResourceManager.GetString("TenantWebDashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to yyyy-MM-ddTHH:mm:ss_fffZ.
        /// </summary>
        internal static string Time_Stamp_Format {
            get {
                return ResourceManager.GetString("Time_Stamp_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to T23:59:59Z.
        /// </summary>
        internal static string To_Date_Append_Time {
            get {
                return ResourceManager.GetString("To_Date_Append_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -900000011.
        /// </summary>
        internal static string TokenRequestFailedErrorCode {
            get {
                return ResourceManager.GetString("TokenRequestFailedErrorCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsInvalidToken.
        /// </summary>
        internal static string TokenRequestFailedQueryString {
            get {
                return ResourceManager.GetString("TokenRequestFailedQueryString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [[[Enter name of the table on Azure storage where all error/exception log, e.g. MatterCenterUILogStorage]]].
        /// </summary>
        internal static string UILogTableName {
            get {
                return ResourceManager.GetString("UILogTableName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /UnpinDocument.
        /// </summary>
        internal static string Unpin_Document {
            get {
                return ResourceManager.GetString("Unpin_Document", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /UnpinMatter.
        /// </summary>
        internal static string Unpin_Matter {
            get {
                return ResourceManager.GetString("Unpin_Matter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Append date to file name and save.
        /// </summary>
        internal static string Upload_Append_Button {
            get {
                return ResourceManager.GetString("Upload_Append_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file will be saved as new, separate document with the current date and time added to the end of the file name..
        /// </summary>
        internal static string Upload_Append_Button_Tooltip {
            get {
                return ResourceManager.GetString("Upload_Append_Button_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Search Matters.
        /// </summary>
        internal static string Upload_Attachments {
            get {
                return ResourceManager.GetString("Upload_Attachments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel upload.
        /// </summary>
        internal static string Upload_Cancel_Button {
            get {
                return ResourceManager.GetString("Upload_Cancel_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This document will not be uploaded and you will return to the previous screen..
        /// </summary>
        internal static string Upload_Cancel_Button_Tooltip {
            get {
                return ResourceManager.GetString("Upload_Cancel_Button_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An issue occurred while reading content check settings. The ability to perform content check is disabled..
        /// </summary>
        internal static string Upload_Content_Check_Setting_Failed {
            get {
                return ResourceManager.GetString("Upload_Content_Check_Setting_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matter Center will compare all content and data associated with the two documents. Navigating away from this screen will cancel the content check..
        /// </summary>
        internal static string Upload_Content_Check_Tooltip {
            get {
                return ResourceManager.GetString("Upload_Content_Check_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perform content check.
        /// </summary>
        internal static string Upload_ContentCheck_Button {
            get {
                return ResourceManager.GetString("Upload_ContentCheck_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        internal static string Upload_Continue_Button {
            get {
                return ResourceManager.GetString("Upload_Continue_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (failed).
        /// </summary>
        internal static string Upload_Failed_Marker {
            get {
                return ResourceManager.GetString("Upload_Failed_Marker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploading mail or mail attachment has failed..
        /// </summary>
        internal static string Upload_Failed_Message {
            get {
                return ResourceManager.GetString("Upload_Failed_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can also drag and drop files from your desktop..
        /// </summary>
        internal static string Upload_Footer_Text {
            get {
                return ResourceManager.GetString("Upload_Footer_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string Upload_Ok_Button {
            get {
                return ResourceManager.GetString("Upload_Ok_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save as latest version.
        /// </summary>
        internal static string Upload_Overwrite_Button {
            get {
                return ResourceManager.GetString("Upload_Overwrite_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file will be saved as the latest version of the existing document that has same title. Matter Center will retain all prior versions of the document..
        /// </summary>
        internal static string Upload_Overwrite_Button_Tooltip {
            get {
                return ResourceManager.GetString("Upload_Overwrite_Button_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload complete..
        /// </summary>
        internal static string Upload_Success_Notification {
            get {
                return ResourceManager.GetString("Upload_Success_Notification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URLReferrer.
        /// </summary>
        internal static string URLReferrerCookieName {
            get {
                return ResourceManager.GetString("URLReferrerCookieName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /User Photos/Profile Pictures/{0}_{1}Thumb.jpg.
        /// </summary>
        internal static string User_Photo_Src {
            get {
                return ResourceManager.GetString("User_Photo_Src", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read.
        /// </summary>
        internal static string User_Upload_Permissions {
            get {
                return ResourceManager.GetString("User_Upload_Permissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /ViewDocument.
        /// </summary>
        internal static string View_Document {
            get {
                return ResourceManager.GetString("View_Document", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /ViewMatter.
        /// </summary>
        internal static string View_Matter {
            get {
                return ResourceManager.GetString("View_Matter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _layouts/15/VisioWebAccess/VisioWebAccess.aspx?id={0}&amp;DefaultItemOpen=1.
        /// </summary>
        internal static string VisioWebAccessUrl {
            get {
                return ResourceManager.GetString("VisioWebAccessUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Word.
        /// </summary>
        internal static string Word {
            get {
                return ResourceManager.GetString("Word", resourceCulture);
            }
        }
    }
}
