//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Legal.MatterCenter.CreateSiteColumns {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SiteColumn_Config {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SiteColumn_Config() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.Legal.MatterCenter.CreateSiteColumns.SiteColumn_Config", typeof(SiteColumn_Config).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Field Type=&quot;TaxonomyFieldTypeMulti&quot; DisplayName=&quot;AreaOfLaw&quot; Description=&quot;This column is a managed metadata column mapped to Area of Law&quot; Required=&quot;FALSE&quot; EnforceUniqueValues=&quot;FALSE&quot; Indexed=&quot;FALSE&quot; MaxLength=&quot;255&quot; Group=&quot;{0}&quot;  StaticName=&quot;AreaOfLaw&quot; Name=&quot;AreaOfLaw&quot; Mult=&quot;TRUE&quot; Hidden=&quot;FALSE&quot; Customization=&quot;&quot; PITarget=&quot;&quot; PrimaryPITarget=&quot;&quot; PIAttribute=&quot;&quot; PrimaryPIAttribute=&quot;&quot; Aggregation=&quot;&quot; Node=&quot;&quot; RowOrdinal=&quot;0&quot; ShowInDisplayForm=&quot;TRUE&quot;&gt;&lt;/Field&gt;.
        /// </summary>
        internal static string AreaOfLaw {
            get {
                return ResourceManager.GetString("AreaOfLaw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Field Type=&quot;Text&quot; DisplayName=&quot;Client_Id&quot; Description=&quot;This is Client Id&quot; Required=&quot;FALSE&quot; EnforceUniqueValues=&quot;FALSE&quot; Indexed=&quot;FALSE&quot; MaxLength=&quot;255&quot; Group=&quot;{0}&quot;  StaticName=&quot;Client_Id&quot; Name=&quot;Client_Id&quot; Hidden=&quot;FALSE&quot; Customization=&quot;&quot; ReadOnly=&quot;TRUE&quot; PITarget=&quot;&quot; PrimaryPITarget=&quot;&quot; PIAttribute=&quot;&quot; PrimaryPIAttribute=&quot;&quot; Aggregation=&quot;&quot; Node=&quot;&quot; ColName=&quot;nvarchar14&quot; RowOrdinal=&quot;0&quot; ShowInDisplayForm=&quot;TRUE&quot;&gt;&lt;/Field&gt;.
        /// </summary>
        internal static string Client_Id {
            get {
                return ResourceManager.GetString("Client_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Field Type=&quot;Text&quot; DisplayName=&quot;Client_Name&quot; Description=&quot;This is the name of the Client&quot; Required=&quot;FALSE&quot; EnforceUniqueValues=&quot;FALSE&quot; Indexed=&quot;FALSE&quot; MaxLength=&quot;255&quot; Group=&quot;{0}&quot;  StaticName=&quot;Client_Name&quot; Name=&quot;Client_Name&quot; Hidden=&quot;FALSE&quot; Customization=&quot;&quot; ReadOnly=&quot;TRUE&quot; PITarget=&quot;&quot; PrimaryPITarget=&quot;&quot; PIAttribute=&quot;&quot; PrimaryPIAttribute=&quot;&quot; Aggregation=&quot;&quot; Node=&quot;&quot; ColName=&quot;nvarchar13&quot; RowOrdinal=&quot;0&quot; ShowInDisplayForm=&quot;TRUE&quot;&gt;&lt;/Field&gt;.
        /// </summary>
        internal static string Client_Name {
            get {
                return ResourceManager.GetString("Client_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Field Type=&quot;Text&quot; DisplayName=&quot;ConversationId&quot; Description=&quot;This column contains id of the conversation&quot; Required=&quot;FALSE&quot; EnforceUniqueValues=&quot;FALSE&quot; Indexed=&quot;FALSE&quot; MaxLength=&quot;255&quot; Group=&quot;{0}&quot;  StaticName=&quot;ConversationId&quot; Name=&quot;ConversationId&quot;&gt;&lt;/Field&gt;.
        /// </summary>
        internal static string ConversationId {
            get {
                return ResourceManager.GetString("ConversationId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Field Type=&quot;Text&quot; DisplayName=&quot;ConversationTopic&quot; Description=&quot;This column contains topic of conversation&quot; Required=&quot;FALSE&quot; EnforceUniqueValues=&quot;FALSE&quot; Indexed=&quot;FALSE&quot; MaxLength=&quot;255&quot; Group=&quot;{0}&quot;  StaticName=&quot;ConversationTopic&quot; Name=&quot;ConversationTopic&quot;&gt;&lt;/Field&gt;.
        /// </summary>
        internal static string ConversationTopic {
            get {
                return ResourceManager.GetString("ConversationTopic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Field Name=&quot;DMS_Attachments&quot; FromBaseType=&quot;FALSE&quot; Type=&quot;Note&quot; DisplayName=&quot;DMS_Attachments&quot; Description=&quot;This column contains the names of the attached documents.&quot; Required=&quot;FALSE&quot; EnforceUniqueValues=&quot;FALSE&quot; Indexed=&quot;FALSE&quot; NumLines=&quot;30&quot; RichText=&quot;FALSE&quot; Sortable=&quot;FALSE&quot; Group=&quot;{0}&quot; StaticName=&quot;DMS_Attachments&quot; RestrictedMode=&quot;TRUE&quot; RichTextMode=&quot;Compatible&quot; IsolateStyles=&quot;FALSE&quot; AppendOnly=&quot;FALSE&quot; UnlimitedLengthInDocumentLibrary=&quot;FALSE&quot;&gt;&lt;/Field&gt;.
        /// </summary>
        internal static string DMS_Attachments {
            get {
                return ResourceManager.GetString("DMS_Attachments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Field Name=&quot;DMS_Cc&quot; FromBaseType=&quot;FALSE&quot; Type=&quot;Note&quot; DisplayName=&quot;DMS_Cc&quot; Description=&quot;This column contains information about the recipients of the email mentioned in Cc.&quot; Required=&quot;FALSE&quot; EnforceUniqueValues=&quot;FALSE&quot; Indexed=&quot;FALSE&quot; NumLines=&quot;6&quot; RichText=&quot;FALSE&quot; Sortable=&quot;FALSE&quot; Group=&quot;{0}&quot; StaticName=&quot;DMS_Cc&quot;&gt;&lt;/Field&gt;.
        /// </summary>
        internal static string DMS_Cc {
            get {
                return ResourceManager.GetString("DMS_Cc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Field Type=&quot;Text&quot; DisplayName=&quot;DMS_From&quot; Description=&quot;This column contains information about the  sender of the email.&quot; Required=&quot;FALSE&quot; EnforceUniqueValues=&quot;FALSE&quot; Indexed=&quot;FALSE&quot; MaxLength=&quot;255&quot; Group=&quot;{0}&quot; StaticName=&quot;DMS_From&quot; Name=&quot;DMS_From&quot;&gt;&lt;/Field&gt;.
        /// </summary>
        internal static string DMS_From {
            get {
                return ResourceManager.GetString("DMS_From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Field Name=&quot;DMS_From_MailBox&quot; FromBaseType=&quot;FALSE&quot; Type=&quot;Text&quot; DisplayName=&quot;DMS_From_MailBox&quot; Description=&quot;This column contains information about the name or email of the user who uploaded the email into the matter library.&quot; Required=&quot;FALSE&quot; EnforceUniqueValues=&quot;FALSE&quot; Indexed=&quot;FALSE&quot; MaxLength=&quot;255&quot; 
        ///
        ///Group=&quot;{0}&quot; StaticName=&quot;DMS_From_MailBox&quot;&gt;&lt;/Field&gt;.
        /// </summary>
        internal static string DMS_From_MailBox {
            get {
                return ResourceManager.GetString("DMS_From_MailBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Field Type=&quot;Text&quot; DisplayName=&quot;DMS_Mail_Importance&quot; Description=&quot;This column contains information about the  importance of the email.&quot; Required=&quot;FALSE&quot; EnforceUniqueValues=&quot;FALSE&quot; Indexed=&quot;FALSE&quot; MaxLength=&quot;255&quot; Group=&quot;{0}&quot; StaticName=&quot;DMS_Mail_Importance&quot; Name=&quot;DMS_Mail_Importance&quot;&gt;&lt;/Field&gt;.
        /// </summary>
        internal static string DMS_Mail_Importance {
            get {
                return ResourceManager.GetString("DMS_Mail_Importance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Field Type=&quot;Note&quot; DisplayName=&quot;DMS_Subject&quot; Description=&quot;This column specifies the subject of the email&quot; Required=&quot;FALSE&quot; EnforceUniqueValues=&quot;FALSE&quot; Indexed=&quot;FALSE&quot; NumLines=&quot;6&quot; RichText=&quot;TRUE&quot; RichTextMode=&quot;FullHtml&quot; IsolateStyles=&quot;TRUE&quot; Sortable=&quot;FALSE&quot; Group=&quot;{0}&quot;  StaticName=&quot;DMS_Subject&quot; Name=&quot;DMS_Subject&quot;&gt;&lt;/Field&gt;.
        /// </summary>
        internal static string DMS_Subject {
            get {
                return ResourceManager.GetString("DMS_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Field Name=&quot;DMS_To&quot; FromBaseType=&quot;FALSE&quot; Type=&quot;Note&quot; DisplayName=&quot;DMS_To&quot; Description=&quot;This column contains information about the receiver of the email.&quot; Required=&quot;FALSE&quot; EnforceUniqueValues=&quot;FALSE&quot; Indexed=&quot;FALSE&quot; NumLines=&quot;6&quot; RichText=&quot;FALSE&quot; Sortable=&quot;FALSE&quot; Group=&quot;{0}&quot; StaticName=&quot;DMS_To&quot;&gt;&lt;/Field&gt;.
        /// </summary>
        internal static string DMS_To {
            get {
                return ResourceManager.GetString("DMS_To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Field Type=&quot;Text&quot; DisplayName=&quot;EmailCategories&quot; Description=&quot;This column contains information about categories of email&quot; Required=&quot;FALSE&quot; EnforceUniqueValues=&quot;FALSE&quot; Indexed=&quot;FALSE&quot; MaxLength=&quot;255&quot; Group=&quot;{0}&quot;  StaticName=&quot;EmailCategories&quot; Name=&quot;EmailCategories&quot;&gt;&lt;/Field&gt;.
        /// </summary>
        internal static string EmailCategories {
            get {
                return ResourceManager.GetString("EmailCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content type already exists.
        /// </summary>
        internal static string ErrContentExists {
            get {
                return ResourceManager.GetString("ErrContentExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to already Exists.
        /// </summary>
        internal static string Exists {
            get {
                return ResourceManager.GetString("Exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Field Type=&quot;Text&quot; DisplayName=&quot;HasAttachments&quot; Description=&quot;This column contains information about attachments of email&quot; Required=&quot;FALSE&quot; EnforceUniqueValues=&quot;FALSE&quot; Indexed=&quot;FALSE&quot; MaxLength=&quot;255&quot; Group=&quot;{0}&quot;  StaticName=&quot;HasAttachments&quot; Name=&quot;HasAttachments&quot;&gt;&lt;/Field&gt;.
        /// </summary>
        internal static string HasAttachments {
            get {
                return ResourceManager.GetString("HasAttachments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Field Type=&quot;Text&quot; DisplayName=&quot;Matter_Id&quot; Required=&quot;FALSE&quot; EnforceUniqueValues=&quot;FALSE&quot; Indexed=&quot;FALSE&quot; MaxLength=&quot;255&quot; Group=&quot;{0}&quot;  StaticName=&quot;Matter_Id&quot; Name=&quot;Matter_Id&quot; Hidden=&quot;FALSE&quot; Customization=&quot;&quot; ReadOnly=&quot;TRUE&quot; PITarget=&quot;&quot; PrimaryPITarget=&quot;&quot; PIAttribute=&quot;&quot; PrimaryPIAttribute=&quot;&quot; Aggregation=&quot;&quot; Node=&quot;&quot; ColName=&quot;nvarchar16&quot; RowOrdinal=&quot;0&quot; ShowInDisplayForm=&quot;TRUE&quot;&gt;&lt;/Field&gt;.
        /// </summary>
        internal static string Matter_Id {
            get {
                return ResourceManager.GetString("Matter_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Field Type=&quot;Text&quot; DisplayName=&quot;Matter_Name&quot; Description=&quot;This is matter name&quot; Required=&quot;FALSE&quot; EnforceUniqueValues=&quot;FALSE&quot; Indexed=&quot;FALSE&quot; MaxLength=&quot;255&quot; Group=&quot;{0}&quot; StaticName=&quot;Matter_Name&quot; Name=&quot;Matter_Name&quot; Hidden=&quot;FALSE&quot; Customization=&quot;&quot; ReadOnly=&quot;TRUE&quot; PITarget=&quot;&quot; PrimaryPITarget=&quot;&quot; PIAttribute=&quot;&quot; PrimaryPIAttribute=&quot;&quot; Aggregation=&quot;&quot; Node=&quot;&quot; ColName=&quot;nvarchar15&quot; RowOrdinal=&quot;0&quot; ShowInDisplayForm=&quot;TRUE&quot;&gt;&lt;/Field&gt;.
        /// </summary>
        internal static string Matter_Name {
            get {
                return ResourceManager.GetString("Matter_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content type created.
        /// </summary>
        internal static string MsgContentTypeCreated {
            get {
                return ResourceManager.GetString("MsgContentTypeCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the name of content type to be created.
        /// </summary>
        internal static string MsgCreateContentType {
            get {
                return ResourceManager.GetString("MsgCreateContentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the name of parent content type.
        /// </summary>
        internal static string MsgParentContentType {
            get {
                return ResourceManager.GetString("MsgParentContentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Field Type=&quot;Note&quot; DisplayName=&quot;OriginalName&quot; Description=&quot;This column specifies the original name of the file&quot; Required=&quot;FALSE&quot; EnforceUniqueValues=&quot;FALSE&quot; Indexed=&quot;FALSE&quot; NumLines=&quot;6&quot; RichText=&quot;TRUE&quot; RichTextMode=&quot;FullHtml&quot; IsolateStyles=&quot;TRUE&quot; Sortable=&quot;FALSE&quot; Group=&quot;{0}&quot;  StaticName=&quot;OriginalName&quot; 
        ///
        ///Name=&quot;OriginalName&quot;&gt;&lt;/Field&gt;.
        /// </summary>
        internal static string OriginalName {
            get {
                return ResourceManager.GetString("OriginalName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Field Type=&quot;TaxonomyFieldTypeMulti&quot; DisplayName=&quot;PracticeGroup&quot; Description=&quot;This column is a managed metadata column mapped to Practice Groups&quot; Required=&quot;FALSE&quot; EnforceUniqueValues=&quot;FALSE&quot; Indexed=&quot;FALSE&quot; MaxLength=&quot;255&quot; Group=&quot;{0}&quot;  StaticName=&quot;PracticeGroup&quot; Name=&quot;PracticeGroup&quot; Mult=&quot;TRUE&quot; Hidden=&quot;FALSE&quot; Customization=&quot;&quot; PITarget=&quot;&quot; PrimaryPITarget=&quot;&quot; PIAttribute=&quot;&quot; PrimaryPIAttribute=&quot;&quot; Aggregation=&quot;&quot; Node=&quot;&quot; RowOrdinal=&quot;0&quot; ShowInDisplayForm=&quot;TRUE&quot;&gt;&lt;/Field&gt;.
        /// </summary>
        internal static string PracticeGroup {
            get {
                return ResourceManager.GetString("PracticeGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Field Name=&quot;ReceivedDate&quot; DisplayName=&quot;ReceivedDate&quot; Type=&quot;DateTime&quot; Description=&quot;This column contains information about the received date of the email.&quot; Required=&quot;FALSE&quot; Group=&quot;{0}&quot; StaticName=&quot;ReceivedDate&quot;&gt;&lt;/Field&gt;.
        /// </summary>
        internal static string ReceivedDate {
            get {
                return ResourceManager.GetString("ReceivedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Field Type=&quot;Text&quot; DisplayName=&quot;Sensitivity&quot; Description=&quot;This column contains information about sensitivity part of email&quot; Required=&quot;FALSE&quot; EnforceUniqueValues=&quot;FALSE&quot; Indexed=&quot;FALSE&quot; MaxLength=&quot;255&quot; Group=&quot;{0}&quot;  StaticName=&quot;Sensitivity&quot; Name=&quot;Sensitivity&quot;&gt;&lt;/Field&gt;.
        /// </summary>
        internal static string Sensitivity {
            get {
                return ResourceManager.GetString("Sensitivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Field Name=&quot;SentDate&quot; DisplayName=&quot;SentDate&quot; Type=&quot;DateTime&quot; Description=&quot;This column contains information about the mail sent date&quot; Required=&quot;FALSE&quot; Group=&quot;{0}&quot; StaticName=&quot;SentDate&quot;&gt;&lt;/Field&gt;.
        /// </summary>
        internal static string SentDate {
            get {
                return ResourceManager.GetString("SentDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matter_Name,Client_Id,Client_Name,Matter_Id,DMS_From,DMS_To,DMS_Cc,DMS_From_MailBox,ReceivedDate,DMS_Subject,DMS_Attachments,DMS_Mail_Importance,Sensitivity,EmailCategories,SentDate,ConversationId,ConversationTopic,HasAttachments,OriginalName,PracticeGroup,AreaOfLaw,SubareaOfLaw.
        /// </summary>
        internal static string SiteColumnNames {
            get {
                return ResourceManager.GetString("SiteColumnNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site Column.
        /// </summary>
        internal static string SiteColumnValue {
            get {
                return ResourceManager.GetString("SiteColumnValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Field Type=&quot;TaxonomyFieldTypeMulti&quot; DisplayName=&quot;SubareaOfLaw&quot; Description=&quot;This column is a managed metadata column mapped to Subarea of Law&quot; Required=&quot;FALSE&quot; EnforceUniqueValues=&quot;FALSE&quot; Indexed=&quot;FALSE&quot; MaxLength=&quot;255&quot; Group=&quot;{0}&quot;  StaticName=&quot;SubareaOfLaw&quot; Name=&quot;SubareaOfLaw&quot; Mult=&quot;TRUE&quot; Hidden=&quot;FALSE&quot; Customization=&quot;&quot; PITarget=&quot;&quot; PrimaryPITarget=&quot;&quot; PIAttribute=&quot;&quot; PrimaryPIAttribute=&quot;&quot; Aggregation=&quot;&quot; Node=&quot;&quot; RowOrdinal=&quot;0&quot; ShowInDisplayForm=&quot;TRUE&quot;&gt;&lt;/Field&gt;.
        /// </summary>
        internal static string SubareaOfLaw {
            get {
                return ResourceManager.GetString("SubareaOfLaw", resourceCulture);
            }
        }
    }
}
