var uiconfigs =
{
  "MatterLanding": {
    "Label1Tab1HeaderText": "Matter Profile",
    "Label2Tab2HeaderText": "Matter Description",
    "Label3Tab1Column1Text": "Client Name",
    "Label4Tab1Column2Text": "Client & Matter ID",
    "Label5Tab1Column3Text": "Practice Group",
    "Label6Tab1Column4Text": "Area of Law",
    "Label7Tab1Column5Text": "Responsible Attorney",
    "Label8Tab1Section2HeaderText": "Matter Library",
    "MenuImageUpperCaption": "Matter Center",
    "MenuImageLowerCaption": "for Office 365",
    "Menu1Option1Text": "Matters",
    "Menu1Option2Text": "Documents",
    "Menu1Option3Text": "Settings",
    "ErrMsg1NoTask": "There are no tasks created",
    "ErrMsg2FetchTask": "Error occurred while trying to fetch tasks",
    "ErrMsg3CreateEvent": "Error occurred while trying to fetch events",
    "ErrMsg4ActiveEvents": "There are no active events",
    "ErrMsg5NoMatterDescription": "There is no description for this matter",
    "ErrMsg6ForPinUnpinMatters": "Error while trying to retrieve matter pin/unpin status",
    "ErrMsg7MatterInformation": "Error while trying to retrieve matter information",
    "ErrMsg8MatterDescription": "Error while trying to retrieve matter description",
    "ErrMsg9NoPinUnpinMatter": "Error while trying to pin/unpin matter",
    "Label1MenuText": "Matter Name",
    "Label9Section1Text": "Matter Id",
    "Label10Section1Text": "Client Id",
    "Label11Section1Text": "Description",
    "Label12ManageUserTitleText": "Manage users",
    "Label13GotoOnnoteTitleText": "Go to Matter OneNote",
    "Label14TaskeTitleText": "Task ",
    "Label15CalenderTitleText": "Calendar Events",
    "Label16RSSFeedTitleText": "Related News (RSS)",
    "Label17EditTitleText": "View / Edit",
    "Label18MenuText": "My Matters",
    "Label19Section4Text": "Matter Library"
  },
  "DocumentDetails": {
    "Label1HeaderText": "File Name",
    "Label2Section2HeaderText": "File Properties",
    "Label3Section2Column1Text": "File title",
    "Label4Section2Column2Text": "Client",
    "Label5Section2Column3Text": "Matter",
    "Label6Section2Column4Text": "Client.MatterID",
    "Label7Section2Column5Text": "Document ID",
    "Label8Section2Column6Text": "Checked out to",
    "Label9Section2Column7Text": "Author",
    "Label10Section2Column8Text": "Date created",
    "Label11Section2Column9Text": "Practice group",
    "Label12Section2Column10Text": "Area of law:",
    "Label13Section2Column11Text": "Sub area of law",
    "Label14Section2Column12Text": "File type",
    "Label15Section2Column13Text": "File size",
    "Label16Section2Column14Text": "File access",
    "Label17Section2HeaderText": "Version history",
    "Label18Section2Column1Text": "Version",
    "Label19Section2Column2Text": "Modified",
    "Label20Section2Column3Text": "Modified By",
    "Label21MenuHeaderOption1Text": "open",
    "Label22MenuHeaderOption2Text": "download",
    "Label23MenuHeaderOption3Text": "share",
    "Label24MenuHeaderOption4Text": "check in",
    "Label25MenuHeaderOption5Text": "check out",
    "Label26MenuHeaderOption6Text": "send link",
    "Label27MenuHeaderOption7Text": "pin",
    "Label28MenuHeaderOption8Text": "unpin",
    "Label1TabTitleText": "Document Details",
    "Link1ErrorDetailsCaptionText": "Click here for details",
    "Link2AllDocumentText": "Go to all documents",
    "LabelNoPreviewText": "There is no preview for this document",
    "ImgNoPreviewSuppoertText": "Preview not supported...",
    "Link3ViewMoreText": "View More",
    "Label135MenuHead" : "OneDrive",
    "Label36MenuHeaderOption7Text" : "Send to OneDrive"
  }
};
