var configs =
{
    "uri": {
        "SPOsiteURL": oEnvironmentConfiguration.tenantUrl,
        "tenant": oEnvironmentConfiguration.tenant,
        "MainURL": "http://www.microsoft.com/mattercenter"
    },
    "ADAL": {
        "clientId": oEnvironmentConfiguration.clientId,
        "authUserEmail": ""
    },
    "appInsights": {
        "instrumentationKey": "0f913235-fa70-4fa4-ae7c-c753d2e0c35d",
        "appType": ""
    },
    "global": {
        "repositoryUrl": oEnvironmentConfiguration.tenantUrl + "/sites/catalog"
    },
    "matter": {
        "StampedPropertyBlockedUploadUsers": "BlockedUploadUsers",
        "StampedPropertyBlockedUsers": "BlockedUsers",
        "StampedPropertyClientID": "ClientID",
        "StampedPropertyClientName": "ClientName",
        "StampedPropertyConflictCheckBy": "MatterConflictCheckBy",
        "StampedPropertyConflictCheckDate": "MatterConflictCheckDate",
        "StampedPropertyDefaultContentType": "MatterCenterDefaultContentType",
        "StampedPropertyDocumentTemplateCount": "DocumentTemplateCount",
        "StampedPropertyIsConflictIdentified": "IsConflictIdentified",
        "StampedPropertyIsMatter": "IsMatter",
        "StampedPropertyMatterCenterPermissions": "MatterCenterPermissions",
        "StampedPropertyMatterCenterRoles": "MatterCenterRoles",
        "StampedPropertyMatterCenterUserEmails": "MatterCenterUserEmails",
        "StampedPropertyMatterCenterUsers": "MatterCenterUsers",
        "StampedPropertyMatterDescription": "MatterDescription",
        "StampedPropertyMatterGUID": "MatterGUID",
        "StampedPropertyMatterID": "MatterID",
        "StampedPropertyMatterName": "MatterName",
        "StampedPropertyOpenDate": "OpenDate",
        "StampedPropertyResponsibleAttorney": "ResponsibleAttorney",
        "StampedPropertyResponsibleAttorneyEmail": "ResponsibleAttorneyEmail",
        "StampedPropertySecureMatter": "SecureMatter",
        "StampedPropertySuccess": "Success",
        "StampedPropertyTeamMembers": "TeamMembers"
    },
    "taxonomy": {
        "levels": "3",
        "termGroup": "MatterCenterTerms",
        "clientTermSetName": "Clients",
        "clientCustomPropertiesURL": "ClientURL",
        "practiceGroupTermSetName": "Practice Groups",
        "subAreaOfLawCustomContentTypeProperty": "ContentTypeName",
        "subAreaOfLawDocumentContentTypeProperty": "DocumentTemplates"
    },
    "search": {
        "ManagedPropertyAreaOfLaw": "MCAreaofLaw",
        "ManagedPropertyAuthor": "MSITOfficeAuthor",
        "ManagedPropertyBlockedUploadUsers": "MCBlockedUploadUser",
        "ManagedPropertyCheckOutByUser": "CheckoutUserOWSUSER",
        "ManagedPropertyClientID": "MCClientID",
        "ManagedPropertyClientName": "MCClientName",
        "ManagedPropertyCreated": "Created",
        "ManagedPropertyCustomTitle": "RefinableString10",
        "ManagedPropertyDescription": "Description",
        "ManagedPropertyDocumentCheckOutUser": "MCCheckoutUser",
        "ManagedPropertyDocumentClientId": "MCDocumentClientID",
        "ManagedPropertyDocumentClientName": "MCDocumentClientName",
        "ManagedPropertyDocumentId": "dlcDocIdOWSText",
        "ManagedPropertyDocumentLastModifiedTime": "MCModifiedDate",
        "ManagedPropertyDocumentMatterId": "RefinableString12",
        "ManagedPropertyDocumentMatterName": "RefinableString13",
        "ManagedPropertyDocumentVersion": "MCVersionNumber",
        "ManagedPropertyFileExtension": "FileExtension",
        "ManagedPropertyFileName": "FileName",
        "ManagedPropertyIsDocument": "IsDocument",
        "ManagedPropertyIsMatter": "MCIsMatter",
        "ManagedPropertyLastModifiedTime": "LastModifiedTime",
        "ManagedPropertyMatterGuid": "MatterCenterMatterGUID",
        "ManagedPropertyMatterGuidLogging": "",
        "ManagedPropertyMatterId": "MCMatterID",
        "ManagedPropertyMatterName": "MCMatterName",
        "ManagedPropertyName": "Name",
        "ManagedPropertyOpenDate": "MCOpenDate",
        "ManagedPropertyPath": "Path",
        "ManagedPropertyPracticeGroup": "MCPracticeGroup",
        "ManagedPropertyResponsibleAttorney": "MCResponsibleAttorney",
        "ManagedPropertyServerRelativeUrl": "ServerRelativeURL",
        "ManagedPropertySiteName": "SiteName",
        "ManagedPropertySiteTitle": "SiteTitle",
        "ManagedPropertySPWebUrl": "SPWebUrl",
        "ManagedPropertySubAreaOfLaw": "MCSubAreaofLaw",
        "ManagedPropertyTeamMembers": "MCTeamMembers",
        "ManagedPropertyTitle": "Title",
        "ManagedPropertyUIVersionStringOWSTEXT": "UIVersionStringOWSTEXT",
        "Schema": "testSchema",
        "searchColumnsUIPickerForMatter": {
            "hideUpload": "test",
            "matterAreaOfLaw": "test",
            "matterClient": "test",
            "matterClientId": "test",
            "matterClientUrl": "test",
            "matterCreatedDate": "test",
            "matterDescription": "test",
            "matterGuid": 154545454545456,
            "matterID": "test",
            "matterModifiedDate": "test",
            "matterName": "test",
            "matterPracticeGroup": "test",
            "matterResponsibleAttorney": "test",
            "matterSubAreaOfLaw": "test",
            "matterUrl": "test"
        },
        "searchColumnsUIPickerForDocument": {
            "documentCheckoutUser": "MAQuser",
            "documentClient": "MAQuser",
            "documentClientId": 1111,
            "documentCreatedDate": 1111,
            "documentExtension": ".xslx",
            "documentIconUrl": "test",
            "documentID": "1213",
            "documentMatter": "test",
            "documentMatterId": "1321",
            "documentMatterName": "test",
            "documentMatterUrl": "test",
            "documentModifiedDate": "656",
            "documentName": { keyName: "documentName", value: "test" },
            "documentOWAUrl": "test",
            "documentOwner": "MAQuser",
            "documentParentUrl": "test",
            "documentUrl": "test",
            "documentVersion": "1.0.1",
            "sitename": "test"
        }
    },
    "contentTypes": {
        "managedColumns": {
            "ColumnName1": "PracticeGroup",
            "ColumnName2": "AreaOfLaw",
            "ColumnName3": "SubareaOfLaw"
        }
    },
    "uploadMessages": {
        "maxAttachedMessage": "Do not select more than five documents to attach at one time.",
        "attachSuccessMessage": "Documents successfully attached.",
        "attachFailureMessage": "One or more of your selected documents failed to attach:",
        "attachButtonText": "Attach Documents",
        "overwrite_Config_Property": "Email Only",
        "upload_Append_Button": "Append date to file name and save",
        "upload_Append_Button_Tooltip": "The file will be saved as new, separate document with the current date and time added to the end of the file name.",
        "content_Check_Abort": "Content check has been aborted.",
        "uploadImageDocumentIcon": "/_layouts/15/images/ic{0}.gif",
        "uploadPNGIconExtensions": "pdf",
        "attachInProgressMessage": ""
    }
}