//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Legal.MatterCenter.SharePointAppWeb.App_LocalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class FindMatter {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FindMatter() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.Legal.MatterCenter.SharePointAppWeb.App_LocalResources.FindMatter", typeof(FindMatter).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search by ID, or matter or client name.
        /// </summary>
        internal static string AutoComplete_Placeholder {
            get {
                return ResourceManager.GetString("AutoComplete_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Forms/AllItems.aspx.
        /// </summary>
        internal static string Document_Library_EndURL {
            get {
                return ResourceManager.GetString("Document_Library_EndURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to get attachment token.
        /// </summary>
        internal static string Fail_Attachment_Token {
            get {
                return ResourceManager.GetString("Fail_Attachment_Token", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matter you are trying to unpin is not pinned..
        /// </summary>
        internal static string Failure_Invalid_Unpin {
            get {
                return ResourceManager.GetString("Failure_Invalid_Unpin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong!.
        /// </summary>
        internal static string Failure_Message {
            get {
                return ResourceManager.GetString("Failure_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no pinned matters..
        /// </summary>
        internal static string Failure_No_Pinned_Matters {
            get {
                return ResourceManager.GetString("Failure_No_Pinned_Matters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MCClientName.
        /// </summary>
        internal static string FilterRefinerClientName {
            get {
                return ResourceManager.GetString("FilterRefinerClientName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MCOpenDate.
        /// </summary>
        internal static string FilterRefinerOpenDate {
            get {
                return ResourceManager.GetString("FilterRefinerOpenDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MatterClient.
        /// </summary>
        internal static string FilterRefinerPinnedClientName {
            get {
                return ResourceManager.GetString("FilterRefinerPinnedClientName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MatterCreatedDate.
        /// </summary>
        internal static string FilterRefinerPinnedCreatedDate {
            get {
                return ResourceManager.GetString("FilterRefinerPinnedCreatedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MatterModifiedDate.
        /// </summary>
        internal static string FilterRefinerPinnedModifiedDate {
            get {
                return ResourceManager.GetString("FilterRefinerPinnedModifiedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MatterResponsibleAttorney.
        /// </summary>
        internal static string FilterRefinerPinnedResponsibleAttorney {
            get {
                return ResourceManager.GetString("FilterRefinerPinnedResponsibleAttorney", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MatterSubAreaOfLaw.
        /// </summary>
        internal static string FilterRefinerPinnedSubAreaofLaw {
            get {
                return ResourceManager.GetString("FilterRefinerPinnedSubAreaofLaw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MCResponsibleAttorney.
        /// </summary>
        internal static string FilterRefinerResponsibleAttorney {
            get {
                return ResourceManager.GetString("FilterRefinerResponsibleAttorney", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MCSubAreaofLaw.
        /// </summary>
        internal static string FilterRefinerSubAreaofLaw {
            get {
                return ResourceManager.GetString("FilterRefinerSubAreaofLaw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to loadNameColumn;loadEllipsisColumn;genericColumn;loadClientMatterID_Column;loadDateColumn;genericColumn;genericColumn;loadDateColumn.
        /// </summary>
        internal static string GridViewColumnFomatter {
            get {
                return ResourceManager.GetString("GridViewColumnFomatter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matter;Client;Client.Matter ID;Modified date;Responsible attorney;Sub area of law;Open date.
        /// </summary>
        internal static string GridViewColumnPickerFields {
            get {
                return ResourceManager.GetString("GridViewColumnPickerFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MCMatterName;ECB;MCClientName;MCClientID;LastModifiedTime;MCResponsibleAttorney;MCSubAreaofLaw;MCOpenDate.
        /// </summary>
        internal static string GridViewColumnValueFields {
            get {
                return ResourceManager.GetString("GridViewColumnValueFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 255;30;210;160;205;260;220;180.
        /// </summary>
        internal static string GridViewColumnWidth {
            get {
                return ResourceManager.GetString("GridViewColumnWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matter,singleselect;ECB,NA;Client,singleselect;Client.Matter ID,NA;Modified date,date.
        /// </summary>
        internal static string GridViewDefaultColumns {
            get {
                return ResourceManager.GetString("GridViewDefaultColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload to this Matter,upload;View Matter Details,gotoMatterSites;Go to Matter OneNote,gotoOneNote;Pin this Matter,pin;Unpin this Matter,unpin.
        /// </summary>
        internal static string GridViewECBActions {
            get {
                return ResourceManager.GetString("GridViewECBActions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload documents to this matter$|$Go to this matter\&apos;s details$|$Go to this matter\&apos;s OneNote$|$Add this matter to Pinned Matters$|$Remove this matter from Pinned Matters.
        /// </summary>
        internal static string GridViewECBActionsTitle {
            get {
                return ResourceManager.GetString("GridViewECBActionsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to view the matter menu.
        /// </summary>
        internal static string GridViewECBMenuTitle {
            get {
                return ResourceManager.GetString("GridViewECBMenuTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matter,singleselect;ECB,NA;Client,singleselect;Client.Matter ID,NA;Modified date,date;Responsible attorney,singleselect;Sub area of law,singleselect;Open date,date.
        /// </summary>
        internal static string GridViewHeaderName {
            get {
                return ResourceManager.GetString("GridViewHeaderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to sort by matter name$|$$|$Click to sort by client name$|$Click to sort by Client.Matter ID$|$Click to sort by last modified date$|$Click to sort by attorney$|$Click to sort by sub area of law$|$Click to sort by matter open date.
        /// </summary>
        internal static string GridViewHeaderNameTitle {
            get {
                return ResourceManager.GetString("GridViewHeaderNameTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MCMatterID.
        /// </summary>
        internal static string GridViewMatterIDPropertyName {
            get {
                return ResourceManager.GetString("GridViewMatterIDPropertyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ECB,NA.
        /// </summary>
        internal static string GridViewNonDataColumns {
            get {
                return ResourceManager.GetString("GridViewNonDataColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CalClientMatterId.
        /// </summary>
        internal static string GridViewPinnedClientMatterIDPropertyName {
            get {
                return ResourceManager.GetString("GridViewPinnedClientMatterIDPropertyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MatterName;ECB;MatterClient;CalClientMatterId;MatterModifiedDate;MatterResponsibleAttorney;MatterSubAreaOfLaw;MatterCreatedDate.
        /// </summary>
        internal static string GridViewPinnedColumnValueFields {
            get {
                return ResourceManager.GetString("GridViewPinnedColumnValueFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MatterClientId.
        /// </summary>
        internal static string GridViewPinnedMatterClientIDPropertyName {
            get {
                return ResourceManager.GetString("GridViewPinnedMatterClientIDPropertyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MatterID.
        /// </summary>
        internal static string GridViewPinnedMatterIDPropertyName {
            get {
                return ResourceManager.GetString("GridViewPinnedMatterIDPropertyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MatterName.
        /// </summary>
        internal static string GridViewPinnedTitleProperty {
            get {
                return ResourceManager.GetString("GridViewPinnedTitleProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MCMatterName.
        /// </summary>
        internal static string GridViewTitleProperty {
            get {
                return ResourceManager.GetString("GridViewTitleProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait while clients are being loaded....
        /// </summary>
        internal static string Loading_Message_Clients {
            get {
                return ResourceManager.GetString("Loading_Message_Clients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait while the matters load..
        /// </summary>
        internal static string Loading_Message_Matters {
            get {
                return ResourceManager.GetString("Loading_Message_Matters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait while pinned matters load..
        /// </summary>
        internal static string Loading_Message_PinnedMatter {
            get {
                return ResourceManager.GetString("Loading_Message_PinnedMatter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to upload document.
        /// </summary>
        internal static string Mail_Upload_Failure {
            get {
                return ResourceManager.GetString("Mail_Upload_Failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document uploaded successfully.
        /// </summary>
        internal static string Mail_Upload_Success {
            get {
                return ResourceManager.GetString("Mail_Upload_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .aspx.
        /// </summary>
        internal static string MatterLandingPageExtension {
            get {
                return ResourceManager.GetString("MatterLandingPageExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No results found..
        /// </summary>
        internal static string No_Data_Message {
            get {
                return ResourceManager.GetString("No_Data_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Untitled.
        /// </summary>
        internal static string No_Subject_Mail {
            get {
                return ResourceManager.GetString("No_Subject_Mail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .onetoc2.
        /// </summary>
        internal static string OneNoteTableOfContentsExtension {
            get {
                return ResourceManager.GetString("OneNoteTableOfContentsExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search matters assigned to Me.
        /// </summary>
        internal static string Search_Assigned_To_Me {
            get {
                return ResourceManager.GetString("Search_Assigned_To_Me", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search entire Matter Center.
        /// </summary>
        internal static string Search_Entire_DMS {
            get {
                return ResourceManager.GetString("Search_Entire_DMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All matters,alldata;My matters,mydata;Pinned matters,pinneddata.
        /// </summary>
        internal static string SearchDropdownFields {
            get {
                return ResourceManager.GetString("SearchDropdownFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong while uploading the file..
        /// </summary>
        internal static string Upload_Failure {
            get {
                return ResourceManager.GetString("Upload_Failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _layouts/WopiFrame.aspx?sourcedoc=.
        /// </summary>
        internal static string WOPIFrameURL {
            get {
                return ResourceManager.GetString("WOPIFrameURL", resourceCulture);
            }
        }
    }
}
