//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Legal.MatterCenter.SharePointAppWeb.App_LocalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LegalBriefcase {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LegalBriefcase() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.Legal.MatterCenter.SharePointAppWeb.App_LocalResources.LegalBriefcase", typeof(LegalBriefcase).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some of the document(s) are checked out to different user.
        /// </summary>
        internal static string CheckIn_Already_Checkout {
            get {
                return ResourceManager.GetString("CheckIn_Already_Checkout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We are working on your changes.
        /// </summary>
        internal static string CheckIn_Message {
            get {
                return ResourceManager.GetString("CheckIn_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some of the document(s) were checked in successfully.
        /// </summary>
        internal static string CheckIn_Partial {
            get {
                return ResourceManager.GetString("CheckIn_Partial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your document has been checked in.
        /// </summary>
        internal static string CheckIn_Success {
            get {
                return ResourceManager.GetString("CheckIn_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check out failed.
        /// </summary>
        internal static string Checkout_Failure {
            get {
                return ResourceManager.GetString("Checkout_Failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We are checking out your file.
        /// </summary>
        internal static string Checkout_Message {
            get {
                return ResourceManager.GetString("Checkout_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You already have the document(s) checked out in the Matter Center Beta.
        /// </summary>
        internal static string CheckOut_Partial_Message {
            get {
                return ResourceManager.GetString("CheckOut_Partial_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your document has been checked out in the Matter Center Beta.
        /// </summary>
        internal static string Checkout_Success {
            get {
                return ResourceManager.GetString("Checkout_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to detach document.
        /// </summary>
        internal static string Detach_Document_Failure {
            get {
                return ResourceManager.GetString("Detach_Document_Failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We are detaching your file from Matter Center Beta.
        /// </summary>
        internal static string Detach_Document_Message {
            get {
                return ResourceManager.GetString("Detach_Document_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are about to detach this file’s connection to Matter Center Beta where it will no longer be able to receive updates or perform actions related to Matter Center Beta. .
        /// </summary>
        internal static string Detach_Document_Question {
            get {
                return ResourceManager.GetString("Detach_Document_Question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your file has been detached.
        /// </summary>
        internal static string Detach_Document_Success {
            get {
                return ResourceManager.GetString("Detach_Document_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detach was successful for some document(s).
        /// </summary>
        internal static string Detach_Partial {
            get {
                return ResourceManager.GetString("Detach_Partial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed!.
        /// </summary>
        internal static string Generic_Failure_Message {
            get {
                return ResourceManager.GetString("Generic_Failure_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success!.
        /// </summary>
        internal static string Generic_Success_Message {
            get {
                return ResourceManager.GetString("Generic_Success_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Good News!.
        /// </summary>
        internal static string Good_News_Message {
            get {
                return ResourceManager.GetString("Good_News_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Legal Briefcase.
        /// </summary>
        internal static string Legal_Briefcase_Folder_Name {
            get {
                return ResourceManager.GetString("Legal_Briefcase_Folder_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can only perform these actions on documents from the Matter Center Beta.
        /// </summary>
        internal static string Not_Supported_Message {
            get {
                return ResourceManager.GetString("Not_Supported_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you wish to continue?.
        /// </summary>
        internal static string Question {
            get {
                return ResourceManager.GetString("Question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sit back and Relax!.
        /// </summary>
        internal static string Relax_Message {
            get {
                return ResourceManager.GetString("Relax_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We are updating your document.
        /// </summary>
        internal static string Update_Copy_Message {
            get {
                return ResourceManager.GetString("Update_Copy_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to update document.
        /// </summary>
        internal static string Update_Document_Failure {
            get {
                return ResourceManager.GetString("Update_Document_Failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some document(s) were updated successfully.
        /// </summary>
        internal static string Update_Document_Partial {
            get {
                return ResourceManager.GetString("Update_Document_Partial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating your copy will overwrite your current OneDrive version and any changes you may have made. .
        /// </summary>
        internal static string Update_Document_Question {
            get {
                return ResourceManager.GetString("Update_Document_Question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your document has been updated.
        /// </summary>
        internal static string Update_Document_Success {
            get {
                return ResourceManager.GetString("Update_Document_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occurred while retrieving version information.
        /// </summary>
        internal static string Version_Info_Failed {
            get {
                return ResourceManager.GetString("Version_Info_Failed", resourceCulture);
            }
        }
    }
}
