//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Legal.MatterCenter.SharePointAppWeb.App_LocalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Settings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Settings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.Legal.MatterCenter.SharePointAppWeb.App_LocalResources.Settings", typeof(Settings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add More.
        /// </summary>
        internal static string Add_More_Link {
            get {
                return ResourceManager.GetString("Add_More_Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some changes have occurred to the settings and your changes were not saved. Refresh the page to view the updated settings.
        /// </summary>
        internal static string Already_Edited_Message {
            get {
                return ResourceManager.GetString("Already_Edited_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Area of law.
        /// </summary>
        internal static string Area_Law_Text {
            get {
                return ResourceManager.GetString("Area_Law_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assign team permission.
        /// </summary>
        internal static string Assign_Team_Permission_Title {
            get {
                return ResourceManager.GetString("Assign_Team_Permission_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel_Button_Text {
            get {
                return ResourceManager.GetString("Cancel_Button_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client Name.
        /// </summary>
        internal static string Client_Name {
            get {
                return ResourceManager.GetString("Client_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}.
        /// </summary>
        internal static string Client_Name_PlaceHolder {
            get {
                return ResourceManager.GetString("Client_Name_PlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string Clients_Header {
            get {
                return ResourceManager.GetString("Clients_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click on a name to configure matter creation options for that client..
        /// </summary>
        internal static string Clients_View_Message {
            get {
                return ResourceManager.GetString("Clients_View_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default selections will be editable when a new matter is created..
        /// </summary>
        internal static string Default_Values_Section_Description {
            get {
                return ResourceManager.GetString("Default_Values_Section_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select default values.
        /// </summary>
        internal static string Default_Values_Section_Title {
            get {
                return ResourceManager.GetString("Default_Values_Section_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string Delete_Icon_Title {
            get {
                return ResourceManager.GetString("Delete_Icon_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter at least one {0} for this matter..
        /// </summary>
        internal static string Error_Mandatory_Role {
            get {
                return ResourceManager.GetString("Error_Mandatory_Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a matter ID..
        /// </summary>
        internal static string Error_Matter_ID {
            get {
                return ResourceManager.GetString("Error_Matter_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a matter name..
        /// </summary>
        internal static string Error_Matter_Title {
            get {
                return ResourceManager.GetString("Error_Matter_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter at least one {0} for this matter..
        /// </summary>
        internal static string Error_Select_User {
            get {
                return ResourceManager.GetString("Error_Select_User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid text which contains only alphanumeric characters, spaces &amp; hyphen.
        /// </summary>
        internal static string Error_Special_Character {
            get {
                return ResourceManager.GetString("Error_Special_Character", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid Matter name which contains only alphanumeric characters and spaces.
        /// </summary>
        internal static string Error_Valid_Matter_Name {
            get {
                return ResourceManager.GetString("Error_Valid_Matter_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        internal static string Icon_Title_Backward {
            get {
                return ResourceManager.GetString("Icon_Title_Backward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string Icon_Title_Forward {
            get {
                return ResourceManager.GetString("Icon_Title_Forward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include calendar?.
        /// </summary>
        internal static string Include_Calendar_Default_Title {
            get {
                return ResourceManager.GetString("Include_Calendar_Default_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include email notification?.
        /// </summary>
        internal static string Include_Email_Notification_Default_Title {
            get {
                return ResourceManager.GetString("Include_Email_Notification_Default_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include RSS Feeds?.
        /// </summary>
        internal static string Include_RSS_Feeds_Default_Title {
            get {
                return ResourceManager.GetString("Include_RSS_Feeds_Default_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include tasks?.
        /// </summary>
        internal static string Include_Tasks_Title {
            get {
                return ResourceManager.GetString("Include_Tasks_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matter Center Portal.
        /// </summary>
        internal static string Matter_Center_Portal_Link {
            get {
                return ResourceManager.GetString("Matter_Center_Portal_Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecting No will remove the conflict check declaration fields from new matters.
        /// </summary>
        internal static string Matter_Conflict_Check_Description {
            get {
                return ResourceManager.GetString("Matter_Conflict_Check_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do matters need conflict check data?.
        /// </summary>
        internal static string Matter_Conflict_Check_Title {
            get {
                return ResourceManager.GetString("Matter_Conflict_Check_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecting No will allow new matters to be saved without a description.
        /// </summary>
        internal static string Matter_Description_Field_Description {
            get {
                return ResourceManager.GetString("Matter_Description_Field_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make the matter description field required?.
        /// </summary>
        internal static string Matter_Description_Required_Title {
            get {
                return ResourceManager.GetString("Matter_Description_Required_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID numbers must be manually entered when a new matter is created. Enter default text, such as ID prefix or suffix, or numbering instructions. This text can be removed or changed when a new matter is created..
        /// </summary>
        internal static string Matter_Id_Default_Description {
            get {
                return ResourceManager.GetString("Matter_Id_Default_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matter ID.
        /// </summary>
        internal static string Matter_Id_Default_Title {
            get {
                return ResourceManager.GetString("Matter_Id_Default_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter default text to appear when a new matter is created. For example, a matter name prefix or suffix, or naming convention instructions.This text can be removed or changed when a new matter is created..
        /// </summary>
        internal static string Matter_Name_Default_Description {
            get {
                return ResourceManager.GetString("Matter_Name_Default_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matter Name.
        /// </summary>
        internal static string Matter_Name_Default_Title {
            get {
                return ResourceManager.GetString("Matter_Name_Default_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected default matter type.
        /// </summary>
        internal static string Matter_Type_Column_Title {
            get {
                return ResourceManager.GetString("Matter_Type_Column_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selection complete? Hide matter type section.
        /// </summary>
        internal static string Matter_Type_Default_Info {
            get {
                return ResourceManager.GetString("Matter_Type_Default_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set a default matter type by selecting a Practice group, Area of law, and Sub areas of law below..
        /// </summary>
        internal static string Matter_Type_Default_Title {
            get {
                return ResourceManager.GetString("Matter_Type_Default_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selection complete? &lt;span class=\&quot;clientLinks\&quot; id=\&quot;hideSection\&quot; title=\&quot;Hide\&quot;&gt;Hide&lt;/span&gt; matter type section.
        /// </summary>
        internal static string Matter_Type_Hidden_Message {
            get {
                return ResourceManager.GetString("Matter_Type_Hidden_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Name_Column_Text {
            get {
                return ResourceManager.GetString("Name_Column_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No clients here!.
        /// </summary>
        internal static string No_Clients_Message {
            get {
                return ResourceManager.GetString("No_Clients_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This page shows the current settings for this client’s new matters. The first section allows you to set new matter default selections, which can be changed when a matter is created. The second section defines settings that can not be changed when a new matter is created. No changes are required, and any changes made will not affect existing matters..
        /// </summary>
        internal static string Page_Default_Description {
            get {
                return ResourceManager.GetString("Page_Default_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permission Level.
        /// </summary>
        internal static string Permission_Column_Text {
            get {
                return ResourceManager.GetString("Permission_Column_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default to restricting access to an assigned team?.
        /// </summary>
        internal static string Restricted_Access_Default_Title {
            get {
                return ResourceManager.GetString("Restricted_Access_Default_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This can be changed when a new matter is created. If you select yes, you can either  define a default team below or leave the team permission blank..
        /// </summary>
        internal static string Restricted_Access_Description {
            get {
                return ResourceManager.GetString("Restricted_Access_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role.
        /// </summary>
        internal static string Role_Column_Text {
            get {
                return ResourceManager.GetString("Role_Column_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string Save_Button_Text {
            get {
                return ResourceManager.GetString("Save_Button_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your changes have been saved. Go back to &lt;span class=\&quot;clientLinks\&quot; id=\&quot;goToClients\&quot; title = \&quot;Clients\&quot;&gt;Clients&lt;/span&gt;..
        /// </summary>
        internal static string Save_Success_Message {
            get {
                return ResourceManager.GetString("Save_Success_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search by Typing.
        /// </summary>
        internal static string Search_By_Typing_Placeholder {
            get {
                return ResourceManager.GetString("Search_By_Typing_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /search/Pages/results.aspx?k={0}.
        /// </summary>
        internal static string Search_Page_URL {
            get {
                return ResourceManager.GetString("Search_Page_URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a Practice Group.
        /// </summary>
        internal static string Select_Practice_Group {
            get {
                return ResourceManager.GetString("Select_Practice_Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected default matter type.
        /// </summary>
        internal static string Selected_Default_Matter_Text {
            get {
                return ResourceManager.GetString("Selected_Default_Matter_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to These settings will not be editable when a new matter is created..
        /// </summary>
        internal static string Set_Matter_Options_Default_Description {
            get {
                return ResourceManager.GetString("Set_Matter_Options_Default_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set matter options.
        /// </summary>
        internal static string Set_Matter_Options_Default_Title {
            get {
                return ResourceManager.GetString("Set_Matter_Options_Default_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /SitePages/Settings.aspx.
        /// </summary>
        internal static string Settings_Page_Url {
            get {
                return ResourceManager.GetString("Settings_Page_Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;span class=\&quot;clientLinks\&quot; id=\&quot;showMatterType\&quot; title=\&quot;Show\&quot;&gt;Show&lt;/span&gt; matter type section.
        /// </summary>
        internal static string Show_Matter_Section {
            get {
                return ResourceManager.GetString("Show_Matter_Section", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show matter type section.
        /// </summary>
        internal static string Show_Matter_Type_Section {
            get {
                return ResourceManager.GetString("Show_Matter_Type_Section", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [A-Za-z0-9_]+[-A-Za-z0-9_, ]*.
        /// </summary>
        internal static string Special_Character_Expression_Matter_Id {
            get {
                return ResourceManager.GetString("Special_Character_Expression_Matter_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [A-Za-z0-9-_]+[A-Za-z0-9-_ ]*.
        /// </summary>
        internal static string Special_Character_Expression_Matter_Title {
            get {
                return ResourceManager.GetString("Special_Character_Expression_Matter_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sub area of law.
        /// </summary>
        internal static string Sub_Area_Law_Text {
            get {
                return ResourceManager.GetString("Sub_Area_Law_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /SitePages/MatterCenterHome.aspx.
        /// </summary>
        internal static string WebDashboard_Page_Url {
            get {
                return ResourceManager.GetString("WebDashboard_Page_Url", resourceCulture);
            }
        }
    }
}
