//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Legal.MatterCenter.SharePointAppWeb.App_LocalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class WebDashboard {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WebDashboard() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.Legal.MatterCenter.SharePointAppWeb.App_LocalResources.WebDashboard", typeof(WebDashboard).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to addCheckBox;loadDocumentTypeIcon;loadNameColumn;loadGenericColumn;loadGenericColumn;changeDateFormat;loadGenericColumn;loadGenericColumn;loadPinIcon.
        /// </summary>
        internal static string DocumentColumnFormatter {
            get {
                return ResourceManager.GetString("DocumentColumnFormatter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CheckBox;FileExtension;FileName;MCDocumentClientName;MSITOfficeAuthor;MCModifiedDate;dlcDocIdOWSText;MCVersionNumber;Pin.
        /// </summary>
        internal static string DocumentColumnValueFields {
            get {
                return ResourceManager.GetString("DocumentColumnValueFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 20;30;200;200;140;160;150;80;30.
        /// </summary>
        internal static string DocumentColumnWidth {
            get {
                return ResourceManager.GetString("DocumentColumnWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View document details.
        /// </summary>
        internal static string DocumentDetailsAction {
            get {
                return ResourceManager.GetString("DocumentDetailsAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FileExtension.
        /// </summary>
        internal static string DocumentExtension {
            get {
                return ResourceManager.GetString("DocumentExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check Box;DocType;Document;Client;Author;Modified date;Document ID;Version;Pin.
        /// </summary>
        internal static string DocumentHeaderName {
            get {
                return ResourceManager.GetString("DocumentHeaderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open document.
        /// </summary>
        internal static string DocumentOpenAction {
            get {
                return ResourceManager.GetString("DocumentOpenAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DocumentOWAUrl.
        /// </summary>
        internal static string DocumentOWAUrl {
            get {
                return ResourceManager.GetString("DocumentOWAUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path.
        /// </summary>
        internal static string DocumentPath {
            get {
                return ResourceManager.GetString("DocumentPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CheckBox;DocumentExtension;DocumentName;DocumentClient;DocumentOwner;DocumentModifiedDate;DocumentID;DocumentVersion;Pin.
        /// </summary>
        internal static string DocumentPinnedColumnValueFields {
            get {
                return ResourceManager.GetString("DocumentPinnedColumnValueFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DocumentName.
        /// </summary>
        internal static string DocumentPinnedTitleProperty {
            get {
                return ResourceManager.GetString("DocumentPinnedTitleProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SPWebUrl.
        /// </summary>
        internal static string DocumentSPWebUrl {
            get {
                return ResourceManager.GetString("DocumentSPWebUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FileName.
        /// </summary>
        internal static string DocumentTitleProperty {
            get {
                return ResourceManager.GetString("DocumentTitleProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong!.
        /// </summary>
        internal static string Failure_Message {
            get {
                return ResourceManager.GetString("Failure_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Enter Redirect URL for Feedback and Support, e.g. mailto:support@supportsite.com].
        /// </summary>
        internal static string Feedback_and_Support {
            get {
                return ResourceManager.GetString("Feedback_and_Support", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 30.
        /// </summary>
        internal static string ItemsPerPage {
            get {
                return ResourceManager.GetString("ItemsPerPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matter Center Document(s).
        /// </summary>
        internal static string Mail_Cart_Mail_Subject {
            get {
                return ResourceManager.GetString("Mail_Cart_Mail_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MatterProvision.aspx.
        /// </summary>
        internal static string Matter_Provision_App_Link {
            get {
                return ResourceManager.GetString("Matter_Provision_App_Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to loadNameColumn;loadGenericColumn;generateClientMatterID;changeDateFormat;loadGenericColumn;loadPinIcon;loadUploadIcon.
        /// </summary>
        internal static string MatterColumnFormatter {
            get {
                return ResourceManager.GetString("MatterColumnFormatter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MCMatterName;MCClientName;MCClientID;LastModifiedTime;MCResponsibleAttorney;Pin;Upload.
        /// </summary>
        internal static string MatterColumnValueFields {
            get {
                return ResourceManager.GetString("MatterColumnValueFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 240;200;150;160;180;30;30.
        /// </summary>
        internal static string MatterColumnWidth {
            get {
                return ResourceManager.GetString("MatterColumnWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View matter details.
        /// </summary>
        internal static string MatterDetailsAction {
            get {
                return ResourceManager.GetString("MatterDetailsAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matter;Client;Client.Matter ID;Modified date;Responsible attorney;Pin;Upload.
        /// </summary>
        internal static string MatterHeaderName {
            get {
                return ResourceManager.GetString("MatterHeaderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RefinableString12.
        /// </summary>
        internal static string MatterIDPropertyForDocument {
            get {
                return ResourceManager.GetString("MatterIDPropertyForDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MCMatterID.
        /// </summary>
        internal static string MatterIDPropertyForMatter {
            get {
                return ResourceManager.GetString("MatterIDPropertyForMatter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .aspx.
        /// </summary>
        internal static string MatterLandingPageExtension {
            get {
                return ResourceManager.GetString("MatterLandingPageExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MatterName;MatterClient;MatterClientId;MatterModifiedDate;MatterResponsibleAttorney;Pin;Upload.
        /// </summary>
        internal static string MatterPinnedColumnValueFields {
            get {
                return ResourceManager.GetString("MatterPinnedColumnValueFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MatterName.
        /// </summary>
        internal static string MatterPinnedTitleProperty {
            get {
                return ResourceManager.GetString("MatterPinnedTitleProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MCMatterName.
        /// </summary>
        internal static string MatterTitleProperty {
            get {
                return ResourceManager.GetString("MatterTitleProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload to a matter.
        /// </summary>
        internal static string MatterUploadAction {
            get {
                return ResourceManager.GetString("MatterUploadAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NA.
        /// </summary>
        internal static string No_Data_String {
            get {
                return ResourceManager.GetString("No_Data_String", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CheckBox;Pin;Upload;FileExtension;DocumentExtension.
        /// </summary>
        internal static string NonDataColumns {
            get {
                return ResourceManager.GetString("NonDataColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no pinned documents..
        /// </summary>
        internal static string NoPinnedDocuments {
            get {
                return ResourceManager.GetString("NoPinnedDocuments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No pinned matters found.
        /// </summary>
        internal static string NoPinnedMatters {
            get {
                return ResourceManager.GetString("NoPinnedMatters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No results found..
        /// </summary>
        internal static string NoResults_Message {
            get {
                return ResourceManager.GetString("NoResults_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .onetoc2.
        /// </summary>
        internal static string OneNoteTableOfContentsExtension {
            get {
                return ResourceManager.GetString("OneNoteTableOfContentsExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DocumentClientId.
        /// </summary>
        internal static string PinnedClientIDPropertyNameForDocument {
            get {
                return ResourceManager.GetString("PinnedClientIDPropertyNameForDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MatterClientId.
        /// </summary>
        internal static string PinnedClientIDPropertyNameForMatter {
            get {
                return ResourceManager.GetString("PinnedClientIDPropertyNameForMatter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DocumentMatterId.
        /// </summary>
        internal static string PinnedMatterIDPropertyNameForDocument {
            get {
                return ResourceManager.GetString("PinnedMatterIDPropertyNameForDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MatterID.
        /// </summary>
        internal static string PinnedMatterIDPropertyNameForMatter {
            get {
                return ResourceManager.GetString("PinnedMatterIDPropertyNameForMatter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Document assigned to Me.
        /// </summary>
        internal static string Search_Assigned_To_Me {
            get {
                return ResourceManager.GetString("Search_Assigned_To_Me", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Documents.
        /// </summary>
        internal static string Search_Documents {
            get {
                return ResourceManager.GetString("Search_Documents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search entire Matter Center.
        /// </summary>
        internal static string Search_Entire_DMS {
            get {
                return ResourceManager.GetString("Search_Entire_DMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Matters.
        /// </summary>
        internal static string Search_Matters {
            get {
                return ResourceManager.GetString("Search_Matters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Matters assigned to Me.
        /// </summary>
        internal static string Search_Matters_Assigned_To_Me {
            get {
                return ResourceManager.GetString("Search_Matters_Assigned_To_Me", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /search/Pages/results.aspx?k={0}.
        /// </summary>
        internal static string Search_Page_URL {
            get {
                return ResourceManager.GetString("Search_Page_URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MatterCenter.
        /// </summary>
        internal static string Temp_Email_Name {
            get {
                return ResourceManager.GetString("Temp_Email_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /sites/contentTypeHub/templates/Forms/AllItems.aspx.
        /// </summary>
        internal static string TemplatesURL {
            get {
                return ResourceManager.GetString("TemplatesURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _layouts/WopiFrame.aspx?sourcedoc=.
        /// </summary>
        internal static string WOPIFrameURL {
            get {
                return ResourceManager.GetString("WOPIFrameURL", resourceCulture);
            }
        }
    }
}
